{
  "hash": "7bfbe2bdd02ac16cd73a8b778be3b61e",
  "result": {
    "engine": "knitr",
    "markdown": "# Meeting Your Data\n\n## Welcome {.unnumbered}\n\n### The data a people analyst actually works with {.unnumbered}\n\nAlmost nothing arrives in one piece. A People Analytics team's data is\nassembled from wherever it happens to live:\n\n-   The **HRIS or HRMS** — Workday, SuccessFactors, BambooHR — holding\n    the core record: who works here, in what role, reporting to whom,\n    since when, on what salary.\n-   **Survey platforms** — engagement, pulse, onboarding, exit — each\n    with its own scale and its own idea of an employee identifier.\n-   **Other HR systems** — the ATS for recruitment, the LMS for\n    learning, performance management, absence, payroll. Rarely\n    designed to talk to each other.\n-   And, always, **spreadsheets**. Someone's headcount tracker.\n    Somebody's list of high-potential employees. The org design work\n    that never made it into a system.\n\nMerging these is a large part of the job, and it's where most of the\nerrors that reach a boardroom are born. This book won't teach you\nthat plumbing — but everything below assumes you're sceptical about\nwhat came out of the other end of it.\n\n### Most of the job is presenting it {.unnumbered}\n\nBe honest about how HR analysis actually gets spent. Think of the\ndashboards and monthly packs that fill HR departments: headcount by\ndivision, attrition against last year, time-to-hire by recruiter,\nengagement scores sliced eleven ways. Producing them consumes an\nenormous share of an analyst's week, and most of it is description —\ncounting, averaging, and drawing bars.\n\nThat work is worth doing well. It's also worth doing *thoughtfully*,\nwhich is the difference this chapter is really about.\n\n### Understand it before you analyse it {.unnumbered}\n\nWhatever you've been asked for, the first move is the same: find out\nwhat you actually have. This is **exploratory data analysis** (EDA) —\na term coined by John Tukey to describe looking at data with an open\nmind before testing anything against it. In practice it's a short list\nof habits:\n\n-   Check the **structure** — how many rows, how many columns, what\n    type is each one, and what does a single row represent?\n-   Check the **gaps** — which values are missing, how many, and is\n    the missingness patterned?\n-   Look at **each variable on its own** — its centre, its spread, its\n    shape.\n-   Hunt for the **impossible and the implausible** — negative tenure,\n    a salary of 1, an engagement score of 9 on a 4-point scale, six\n    people reporting to themselves.\n-   Look at **variables in pairs** — does anything move together in a\n    way you didn't expect?\n-   **Sense-check against the business.** You know roughly how many\n    people work here. Does the data agree?\n\nNone of that is glamorous, and all of it is faster than explaining a\nwrong number afterwards.\n\n### Always ask why they're asking {.unnumbered}\n\nEven when the request is purely descriptive — *\"can you send me\nattrition by department for the last six quarters?\"* — the great\nanalyst does one more thing before opening the data: works out **what\nthe person is going to do with it**.\n\nNobody wants a table. They want to decide something, or defend\nsomething, or reassure someone. Once you know which, you can often\noffer an approach that serves them better than the one they asked for\n— and that's the difference between an analyst who fields requests\nand one who gets invited to the conversation earlier.\n\n::: callout-note\nThis matters more than it sounds, and it's not a soft skill. We come\nback to it at the end of this chapter, because there's a specific,\npredictable thing people are usually doing with historical data — and\nthey're usually doing it badly.\n:::\n\n### How to read this chapter {.unnumbered}\n\nAs we talk through each idea, run the code chunk next to it, change a\nnumber, and see what happens. This chapter follows the same rhythm\nevery chapter in this book will: a little theory, a lot of code you can\npoke at.\n\nToday is deliberately gentle: **no models, no probability, no maths**.\nWe meet the two datasets we'll use throughout the book, and learn to\n*describe* data.\n\n## What you'll be able to do by the end {.unnumbered}\n\n1.  Load a dataset into R and inspect its structure\n2.  Tell **categorical** from **numeric** variables — and why it matters\n3.  Describe a numeric variable with **centre** and **spread**\n4.  Describe a categorical variable with **counts** and **proportions**\n5.  Read histograms, boxplots, violin plots and bar charts — and know\n    which to put in front of a manager\n6.  Explain why a request for historical data is usually a question\n    about the future\n\n## Why start here? {.unnumbered}\n\n::: callout-important\nEvery analysis begins by describing the data. Before anyone believes\nyour model, they want to know you **understand what you're working\nwith**. Most analytical mistakes are made before any model is fitted,\nby someone who didn't look at their data first.\n:::\n\n------------------------------------------------------------------------\n\n## Setup\n\n::: callout-tip\n## Before you start\n\nIf you intend to run the code as you read — and if R is new to you, you\nshould — have R and an editor installed and open before you go any\nfurther. @sec-getting-started-with-r walks through it: where to download R and\nRStudio (or Positron) from, which packages to install, and the\nbrowser-based option if you would rather not install anything at all.\nIt also explains what `tidyverse` and `brms` actually are, since this\nbook otherwise treats both as furniture.\n\nIf you would rather read than type, that is a legitimate way to use\nthis book. @sec-r-how-to-use sets out which approach suits which\nreader.\n:::\n\nWe load the tidyverse, set a consistent plot theme, and load our two\nrunning datasets from the `peopleanalyticsdata` package (created by\nKeith McNulty — see the [Welcome](../index.qmd) chapter for the full\ncredit). **This same setup block appears, in spirit, at the top of\nevery chapter in this book.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(peopleanalyticsdata)\nlibrary(skimr)\n\ntheme_set(theme_minimal(base_size = 13))\n\ndata(\"salespeople\", package = \"peopleanalyticsdata\")\ndata(\"employee_survey\", package = \"peopleanalyticsdata\")\n```\n:::\n\n\n::: callout-tip\n## If you get a \"package not found\" error\n\nA **package** is a bundle of functions somebody else wrote and shared;\n`library()` loads one that is already on your machine, but it has to be\ninstalled first. Run this **once** in the console (the pane you type\ninto directly), not in a code chunk:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\"tidyverse\", \"peopleanalyticsdata\", \"skimr\"))\n```\n:::\n\n\nSee @sec-r-install if that fails.\n:::\n\n------------------------------------------------------------------------\n\n## What *is* a dataset?\n\n### Rows and columns\n\nA dataset is just a table:\n\n-   Each **row** is one *observation* — one thing you measured\n-   Each **column** is one *variable* — one thing you measured *about*\n    it\n-   Each **cell** is one *value*\n\nThat three-part description has a name: **tidy data**. It's the\nconvention the whole tidyverse — `dplyr`, `ggplot2`, and everything\nelse we use — is built around, and it's why those tools compose so\nneatly. Give a tidy table to `group_by()`, `summarise()` or `ggplot()`\nand it will do the obvious thing without argument.\n\n::: callout-note\n## Tidy for analysis, not necessarily for reading\n\nConveniently, tidy is roughly how HR systems already store data. An\nHRIS keeps one row per employee, or one row per absence event, or one\nrow per survey response — because that's the sane way to store\nrecords.\n\nInconveniently, it's often the *worst* way to present them. Nobody\nwants a thousand-row table. A manager wants absence rates as a small\ngrid of departments down the side and months across the top — which\nis emphatically not tidy, because the column headings have become\ndata.\n\nBoth shapes are correct for their purpose. Analyse long, present wide,\nand use `pivot_longer()` and `pivot_wider()` to move between them.\n:::\n\n::: callout-important\n## The sentence you must always be able to finish\n\n**\"One row is one \\_\\_\\_.\"**\n\nGet this wrong and every number that follows is wrong. In\n`salespeople`, one row is one **salesperson**.\n:::\n\n### Our two datasets\n\nWe'll use these two throughout the book, so it's worth learning them\nproperly.\n\n-   **`salespeople`** — one row per salesperson. Sales figures,\n    customer ratings, performance, and whether they were promoted.\n    Used to ask *\"what predicts who gets promoted?\"*\n-   **`employee_survey`** — one row per **survey response** to an\n    engagement survey, on a four-point scale. This is *survey data* —\n    exactly the shape most People Analytics teams collect constantly.\n\n### A first look\n\n`glimpse()` shows the structure: every column, its type, and the first\nfew values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(salespeople)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 351\nColumns: 4\n$ promoted      <int> 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,…\n$ sales         <int> 594, 446, 674, 525, 657, 918, 318, 364, 342, 387, 527, 7…\n$ customer_rate <dbl> 3.94, 4.06, 3.83, 3.62, 4.40, 4.54, 3.09, 4.89, 3.74, 3.…\n$ performance   <int> 2, 3, 4, 2, 3, 2, 3, 1, 3, 3, 3, 3, 2, 3, 2, 3, 1, 4, 2,…\n```\n\n\n:::\n:::\n\n\nSo we have 351 salespeople described by\n4 variables.\n\n`glimpse()` answers *what columns do I have*. It deliberately does not\ntell you what is **in** them — that comes shortly, with `skim()`, which is\nthe tool we use for the fuller look. Two functions, two jobs, and it is\nworth keeping them separate in your head.\n\n### Two kinds of variable\n\nThis distinction drives every choice you make later.\n\n| | **Numeric** | **Categorical** |\n|---|---|---|\n| Meaning | arithmetic makes sense | a label for a group |\n| Examples | `sales`, `customer_rate` | `promoted`, `performance` |\n| Describe with | centre and spread | counts |\n| Picture | histogram, boxplot | bar chart |\n\nAveraging `performance` (a 1–4 rating) is defensible only if you're\ncomfortable treating it as a genuine number rather than an ordered\nlabel — we'll come back to exactly that question, properly, in Chapter 18. For now, treat it as categorical.\n\n### The other dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(employee_survey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2,833\nColumns: 14\n$ Happiness <int> 4, 3, 4, 4, 3, 4, 3, 4, 4, 4, 4, 4, 3, 4, 4, 4, 3, 4, 4, 4, …\n$ Ben1      <int> 4, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 4, 3, 2, 4, 4, 3, …\n$ Ben2      <int> 4, 3, 4, 4, 3, 4, 3, 3, 4, 4, 4, 4, 3, 4, 4, 4, 3, 4, 4, 3, …\n$ Ben3      <int> 4, 3, 4, 3, 3, 4, 3, 3, 4, 4, 4, 4, 3, 4, 4, 4, 3, 4, 4, 3, …\n$ Work1     <int> 4, 3, 2, 3, 2, 4, 2, 3, 3, 4, 4, 3, 3, 3, 3, 3, 2, 3, 3, 3, …\n$ Work2     <int> 4, 3, 2, 3, 2, 4, 1, 2, 3, 4, 3, 3, 2, 2, 2, 2, 3, 2, 3, 3, …\n$ Work3     <int> 3, 3, 2, 3, 1, 4, 1, 2, 2, 2, 3, 3, 2, 3, 2, 3, 3, 2, 3, 3, …\n$ Man1      <int> 4, 4, 2, 3, 3, 4, 2, 3, 4, 4, 4, 4, 2, 4, 4, 3, 2, 3, 4, 4, …\n$ Man2      <int> 4, 4, 3, 4, 3, 4, 2, 3, 3, 4, 3, 4, 3, 4, 4, 4, 3, 4, 4, 4, …\n$ Man3      <int> 4, 4, 3, 4, 3, 4, 2, 3, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, …\n$ Car1      <int> 4, 4, 3, 4, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 4, 3, …\n$ Car2      <int> 4, 3, 4, 4, 2, 4, 3, 4, 4, 4, 4, 4, 4, 3, 4, 4, 2, 4, 4, 4, …\n$ Car3      <int> 4, 4, 2, 4, 2, 4, 3, 4, 4, 4, 4, 4, 3, 3, 4, 4, 2, 4, 4, 3, …\n$ Car4      <int> 4, 4, 3, 4, 2, 4, 3, 4, 4, 4, 4, 4, 3, 3, 4, 3, 2, 3, 4, 3, …\n```\n\n\n:::\n:::\n\n\n### Your turn {.unnumbered}\n\nLook at that output and answer three questions before reading on. What\ndoes **one row** represent — and how do you know? Why are there so many\nmore rows here than in `salespeople`? And are these columns numeric or\ncategorical, given every one of them holds a whole number from 1 to 4?\n\nThe third question is genuinely hard, and it's the one Chapter 18 is\nbuilt around.\n\n------------------------------------------------------------------------\n\n## Describing a number\n\n### Two questions, always\n\nFor any numeric variable, ask:\n\n1.  **Where is the middle?** — the typical value\n2.  **How spread out is it?** — how much values vary\n\nAnswer both and you've described it. Everything else is detail.\n\n### Mean vs median\n\nTwo ways to say \"the middle\":\n\n-   The **mean** adds everything and divides — every value affects it,\n    including extreme ones\n-   The **median** is the middle value when sorted — it ignores *how*\n    extreme the extremes are\n\nWhen someone says \"average\" they almost always mean the **mean** —\nit's what `AVERAGE()` computes in Excel, and it's what a stakeholder\npictures when they ask for one. That's fine when the data is roughly\nsymmetric, and misleading when it isn't.\n\n### Which one, in HR {.unnumbered}\n\nThe choice is usually decided by whether a long tail exists:\n\n-   **Salary → median.** Pay distributions are right-skewed: a handful\n    of senior people pull the mean above what almost anyone earns. It\n    is not an accident that UK gender pay gap reporting requires\n    organisations to publish **both** the mean and the median gap —\n    the pair tells you something neither does alone, and a large\n    difference between them is itself a finding about how pay is\n    distributed.\n-   **Tenure → median.** A few twenty-year veterans will drag the mean\n    somewhere no current employee actually sits.\n-   **Time to hire → median.** One requisition open for eleven months\n    can add a fortnight to the mean across a whole quarter.\n-   **Absence days → median**, usually, and often better still as a\n    distribution: most people take very few days, a small number take\n    many.\n-   **Engagement scores → mean is fine.** The scale is often bounded 1 to 5,\n    so there's no long tail to distort anything, and means are easier to\n    compare across teams.\n\n::: callout-important\nIf you're not sure, compute both. If they agree, report the mean and\nmove on. If they don't, you've learned something about the shape of\nyour data that you needed to know anyway.\n:::\n\n::: callout-note\n## Why the difference matters\n\nNine salespeople sell \\$40,000 each and one sells \\$2,000,000. The\n**mean** is a figure nobody near actually sold. The **median** is\n\\$40,000.\n\nWhich better describes a typical salesperson?\n:::\n\n### The numbers for sales\n\n`glimpse()` told us what the columns *are*. To see what is *in* them,\nthe one-line answer is `skim()`, from the `skimr` package:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskim(salespeople)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |            |\n|:------------------------|:-----------|\n|Name                     |salespeople |\n|Number of rows           |351         |\n|Number of columns        |4           |\n|_______________________  |            |\n|Column type frequency:   |            |\n|numeric                  |4           |\n|________________________ |            |\n|Group variables          |None        |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|   mean|     sd|  p0|    p25|    p50|    p75| p100|hist  |\n|:-------------|---------:|-------------:|------:|------:|---:|------:|------:|------:|----:|:-----|\n|promoted      |         0|             1|   0.32|   0.47|   0|   0.00|   0.00|   1.00|    1|▇▁▁▁▃ |\n|sales         |         1|             1| 527.01| 185.22| 151| 389.25| 475.00| 667.25|  945|▂▇▅▃▃ |\n|customer_rate |         1|             1|   3.61|   0.89|   1|   3.00|   3.62|   4.29|    5|▁▃▆▇▆ |\n|performance   |         1|             1|   2.50|   0.95|   1|   2.00|   3.00|   3.00|    4|▃▇▁▇▃ |\n\n\n:::\n:::\n\n\nThat is a lot of table at once, so read it in this order.\n\n**`n_missing` first.** It counts the empty cells in each column, and it\nis the reason for the `na.rm = TRUE` arguments you are about to meet —\n`na.rm` is short for \"**NA rem**ove\", `NA` being R's marker for a\nmissing value, so the whole argument reads as *remove the missing\nvalues before calculating*. We come back to it properly at the end of\nthe chapter. Getting this on screen in the first minute, rather than\ndiscovering it later, is the main reason this book uses `skim()` rather\nthan the shorter `summary()`.\n\n::: callout-tip\n## Most names in R are squashed-up words\n\n`na.rm`, `sd`, `IQR`, `cumsum`, `rbinom` — almost every function and\nargument name in R is an abbreviated description of what it does (`sd`\n= standard deviation, `cumsum` = cumulative sum). Reading them that way\nmeans you can often guess a new one correctly on sight, which is a far\nbetter position than looking up every term. When the guess fails,\ntyping `?name` in the console — `?mutate`, `?rbinom` — opens the\ndocumentation, and the **Examples** at the bottom of the page are\nusually the fastest way in.\n:::\n\n**Then the middle.** `mean` is the mean and `p50` is the median. When\nthose two disagree, the column is skewed — the distinction we were just\ndrawing, now visible for every column at once.\n\n**Then the two ends.** `p0` and `p100` are the smallest and largest\nvalues, and this is where impossible numbers show themselves: a negative\ntenure, a salary of 1, an engagement score of 9 on a four-point scale.\n\n`skim()` also groups its output by variable type, giving character\ncolumns and numeric columns separate tables with different summaries.\nHere there is only one table, because every column in `salespeople` is\nstored as a number. That includes `performance`, which is really a 1--4\nrating: a category stored as a number. Neither `skim()` nor R can tell\nthe difference, which is exactly why the numeric-versus-categorical\njudgement earlier in this chapter is yours to make rather than the\ncomputer's.\n\nThe tidyverse version is more typing but composes with everything else:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalespeople |>\n  summarise(\n    mean_sales   = mean(sales, na.rm = TRUE),\n    median_sales = median(sales, na.rm = TRUE),\n    sd_sales     = sd(sales, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  mean_sales median_sales sd_sales\n1   527.0057          475 185.2245\n```\n\n\n:::\n:::\n\n\n::: callout-tip\n## What `na.rm = TRUE` is doing there\n\n`sales` has a missing value in it, and R's summary functions **refuse\nto guess**. Without `na.rm = TRUE` they hand back `NA` instead of a\nnumber — or, in `quantile()`'s case, an outright error.\n\nTreat `na.rm = TRUE` as a habit worth having by default whenever you\nsummarise real data. The last section of this chapter explains why\nit's a habit rather than a fix.\n:::\n\nThe **mean** is 527 and\nthe **median** is 475\n(both in thousands of dollars).\n\n### See it: the histogram\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(salespeople, aes(x = sales)) +\n  geom_histogram(bins = 30, fill = \"#122a52\", alpha = 0.45, colour = \"white\") +\n  geom_vline(xintercept = mean(salespeople$sales, na.rm = TRUE),\n             colour = \"#8a5a00\", linewidth = 1) +                    # <1>\n  geom_vline(xintercept = median(salespeople$sales, na.rm = TRUE),\n             colour = \"#8a5a00\", linewidth = 1, linetype = \"dashed\") +\n  labs(\n    title = \"Distribution of sales\",\n    subtitle = \"Solid line = mean, dashed line = median\",\n    x = \"Sales (thousands of dollars)\", y = \"Number of salespeople\"\n  )\n```\n\n::: {.cell-output-display}\n![](01-meeting-your-data_files/figure-html/sales-histogram-1.png){width=672}\n:::\n:::\n\n\n1.  Amber, and the same amber for both. The two lines are the *point* of\n    this chart, so they need to read clearly against the navy bars —\n    which a soft grey does not. **Linetype**, not colour, separates the\n    mean from the median, so that the pair still reads as one idea.\n\n### What the shape tells you\n\nMost salespeople cluster in the middle, with a **tail of high\nperformers** stretching to the right — that tail is exactly why the\nmean sits *above* the median.\n\n::: callout-important\nWhen the mean and median disagree, the data is **skewed** — and you\nshould report both.\n:::\n\n### Spread: two measures\n\n-   **Standard deviation (SD)** — roughly the typical distance from the\n    mean. It pairs with the mean, and like the mean it is pulled by\n    every extreme value.\n-   **Interquartile range (IQR)** — the range covering the middle 50%\n    of the data, from the 25th to the 75th percentile. It pairs with\n    the median, and like the median it is barely affected by extremes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalespeople |>\n  summarise(\n    sd  = sd(sales, na.rm = TRUE),\n    q25 = quantile(sales, probs = 0.25, na.rm = TRUE),\n    q75 = quantile(sales, probs = 0.75, na.rm = TRUE),\n    iqr = IQR(sales, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        sd    q25    q75 iqr\n1 185.2245 389.25 667.25 278\n```\n\n\n:::\n:::\n\n\nNote the pairing. If you report a **mean**, report an **SD** next to\nit; if you report a **median**, report the **IQR**. Mixing them —\na median with a standard deviation — is a small tell that someone\nreached for whichever number came to hand.\n\n### The boxplot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(salespeople, aes(y = sales)) +\n  geom_boxplot(fill = \"#122a52\", alpha = 0.8) +\n  labs(title = \"Sales — boxplot\", y = \"Sales (thousands of dollars)\", x = NULL) +\n  theme(axis.text.x = element_blank())\n```\n\n::: {.cell-output-display}\n![](01-meeting-your-data_files/figure-html/sales-boxplot-1.png){width=672}\n:::\n:::\n\n\n### Reading it, and when not to use it\n\nA boxplot is a **five-number summary** drawn to scale. The box runs\nfrom the 25th to the 75th percentile — so the box *is* the IQR, and\nthe middle half of your salespeople sit inside it. The line across the\nbox is the median. The whiskers reach out to the furthest points\nwithin 1.5 × IQR of the box, and anything beyond that is drawn as an\nindividual dot.\n\nAnalysts love these, for good reasons: they're compact, they encode\nfive numbers plus outliers in almost no ink, and — the real\nattraction — you can line up eight of them side by side and compare\ngroups at a glance.\n\n::: callout-important\n## Why they often fail in front of a manager\n\nThree problems, and they compound:\n\n1.  **They need explaining.** If you have to say \"the whiskers are 1.5\n    times the interquartile range\" out loud in a meeting, you've spent\n    your audience's attention on the chart instead of the finding.\n2.  **They hide the shape.** A boxplot of a two-humped distribution —\n    say, a team split between long-tenured staff and a recent intake —\n    looks identical to a boxplot of a single broad group. That's a\n    genuinely important difference to conceal.\n3.  **They hide the sample size.** A box drawn from six people looks\n    exactly as solid as one drawn from six hundred. In People\n    Analytics, where team sizes vary wildly, this is the dangerous\n    one — and it's the problem Chapters 8, 14 and 15 exist to solve\n    properly.\n:::\n\n### The violin plot\n\nA **violin plot** solves the first two by drawing the actual shape of\nthe distribution — a smoothed histogram, mirrored to make it\nsymmetric. Wide means many people at that value; narrow means few.\nMost people read one correctly without instruction, because width\nmaps onto \"how many\" the way intuition expects.\n\nYou don't have to choose. The usual recommendation is both — the\nviolin for the shape, a slim boxplot inside it for the summary\nstatistics:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(salespeople, aes(x = \"\", y = sales)) +\n  geom_violin(fill = \"#122a52\", alpha = 0.30, colour = \"#122a52\") +\n  geom_boxplot(width = 0.12, fill = \"white\", outlier.shape = NA) +   # <1>\n  labs(title = \"Sales — violin plot with boxplot inside\",\n       subtitle = \"The shape shows where salespeople actually pile up\",\n       y = \"Sales (thousands of dollars)\", x = NULL)\n```\n\n::: {.cell-output-display}\n![](01-meeting-your-data_files/figure-html/sales-violin-1.png){width=672}\n:::\n:::\n\n\n1.  `outlier.shape = NA` suppresses the boxplot's outlier dots, since\n    the violin already shows the tails. Without it you'd draw the same\n    extreme salespeople twice.\n\nCompare the two figures. The boxplot says sales are right-skewed. The\nviolin shows you *how* — a dense cluster of salespeople around 400,\nthinning steadily upward, with no second group hiding anywhere.\n\n::: callout-tip\nWhichever you use, add the group size to the axis label — `Sales team\n(n = 42)` — or plot the individual points on top when there are few\nenough. It costs nothing and it stops a six-person team being read\nwith the same confidence as a six-hundred-person one.\n:::\n\n------------------------------------------------------------------------\n\n## Describing a category\n\n### Count, don't average\n\nThere's no \"average performance rating\" that means much on its own.\nInstead we ask: **how many** fall into each group, and **what share**\nis that?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalespeople |>\n  count(performance) |>\n  mutate(proportion = round(n / sum(n), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  performance   n proportion\n1           1  60      0.171\n2           2 110      0.313\n3           3 125      0.356\n4           4  55      0.157\n5          NA   1      0.003\n```\n\n\n:::\n:::\n\n\n### The bar chart\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalespeople |>\n  count(performance) |>\n  ggplot(aes(x = factor(performance), y = n)) +\n  geom_col(fill = \"#122a52\") +\n  labs(title = \"Performance ratings across the sales team\",\n       x = \"Performance rating (1 = lowest, 4 = highest)\", y = \"Number of salespeople\")\n```\n\n::: {.cell-output-display}\n![](01-meeting-your-data_files/figure-html/performance-bar-1.png){width=672}\n:::\n:::\n\n\n### Bars vs histograms\n\n::: callout-tip\n## Don't mix them up\n\n-   A **bar chart** shows counts for a handful of **labels**. Gaps\n    between bars are meaningful.\n-   A **histogram** shows the shape of a **numeric** variable. Bars\n    touch because the underlying scale is continuous.\n:::\n\n### Your turn {.unnumbered}\n\nMake the same count-and-bar-chart for `promoted`. What share of the\nsales team was promoted?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your code here\n```\n:::\n\n\n------------------------------------------------------------------------\n\n## The survey data\n\n### Meet the engagement survey\n\nEach row is one employee's response, with an overall `Happiness` score\n(1–4) and several sub-scale items on the same scale: benefits (`Ben1-3`),\nwork environment (`Work1-3`), management (`Man1-3`), and career\nprospects (`Car1-4`).\n\n::: callout-note\nThis is exactly the shape of an engagement survey you'll meet in real\nPeople Analytics work — which is why we'll keep coming back to it.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemployee_survey |>\n  summarise(\n    mean_happiness   = mean(Happiness, na.rm = TRUE),\n    median_happiness = median(Happiness, na.rm = TRUE),\n    sd_happiness     = sd(Happiness, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  mean_happiness median_happiness sd_happiness\n1       3.537593                4    0.6334169\n```\n\n\n:::\n:::\n\n\n### How employees rate their happiness\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(employee_survey, aes(x = factor(Happiness))) +\n  geom_bar(fill = \"#122a52\") +\n  labs(title = \"Overall happiness (1–4)\",\n       x = \"Happiness rating\", y = \"Number of responses\")\n```\n\n::: {.cell-output-display}\n![](01-meeting-your-data_files/figure-html/survey-bar-1.png){width=672}\n:::\n:::\n\n\n### Why that shape matters\n\nSurvey scores are **bounded** (they can't go below 1 or above 4) and\noften **pile up toward one end**.\n\n::: callout-important\nKeep that shape in mind. It's extremely common in engagement data, it\nbreaks some standard modelling assumptions, and it's exactly why\nChapter 18 exists.\n:::\n\n------------------------------------------------------------------------\n\n## A first look at relationships\n\nDescription gets interesting when we ask whether one variable *differs\nacross* another. We're not modelling yet — just looking.\n\n### Does sales differ by promotion outcome?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalespeople |>\n  group_by(promoted) |>\n  summarise(\n    mean_sales = mean(sales, na.rm = TRUE),\n    median_sales = median(sales, na.rm = TRUE),\n    n = n()\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  promoted mean_sales median_sales     n\n     <int>      <dbl>        <int> <int>\n1        0       418.          418   238\n2        1       755.          753   113\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(salespeople, aes(x = factor(promoted), y = sales, fill = factor(promoted))) +\n  geom_boxplot(alpha = 0.85, show.legend = FALSE) +\n  scale_fill_manual(values = c(\"#122a52\", \"#3d68a8\")) +\n  labs(title = \"Sales by promotion outcome\",\n       subtitle = \"Promoted salespeople sell more — but is that the whole story?\",\n       x = \"Promoted (1 = yes, 0 = no)\", y = \"Sales (thousands of dollars)\")\n```\n\n::: {.cell-output-display}\n![](01-meeting-your-data_files/figure-html/sales-by-promoted-plot-1.png){width=672}\n:::\n:::\n\n\nThat question — *is that the whole story?* — is what the rest of this\nbook teaches you to answer properly.\n\n### A trick worth knowing\n\nBecause `promoted` is coded 0/1, its **mean is the promotion rate**.\nWe'll lean on this constantly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalespeople |>\n  group_by(performance) |>\n  summarise(\n    n = n(),\n    promotion_rate = mean(promoted, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  performance     n promotion_rate\n        <int> <int>          <dbl>\n1           1    60          0.167\n2           2   110          0.227\n3           3   125          0.384\n4           4    55          0.545\n5          NA     1          0    \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsalespeople |>\n  group_by(performance) |>\n  summarise(promotion_rate = mean(promoted, na.rm = TRUE)) |>\n  ggplot(aes(x = factor(performance), y = promotion_rate)) +\n  geom_col(fill = \"#122a52\") +\n  scale_y_continuous(labels = scales::percent) +\n  labs(title = \"Promotion rate by performance rating\",\n       x = \"Performance rating\", y = \"Promotion rate\")\n```\n\n::: {.cell-output-display}\n![](01-meeting-your-data_files/figure-html/promotion-rate-plot-1.png){width=672}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Messy reality: missing values\n\nReal organisational data is rarely as clean as it first looks — and,\nin fact, neither is this teaching dataset. Let's check what we're\nactually working with:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolSums(is.na(salespeople))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     promoted         sales customer_rate   performance \n            0             1             1             1 \n```\n\n\n:::\n:::\n\n\nOne missing value in `sales`, one in `customer_rate`, one in\n`performance`, none in `promoted`. Out of 351 rows\nthat's almost\nnothing — and it's still enough to turn a mean into `NA`, which is\nexactly why the calculations earlier in this chapter used\n`na.rm = TRUE`.\n\nNotice too that the gaps aren't only in `sales`. Had we checked only\nthe column we happened to be summarising, we'd have missed two of\nthem.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(some_vector)                 # returns NA if anything is missing\nmean(some_vector, na.rm = TRUE)   # ignores the missing values\nquantile(some_vector, probs = 0.25)                 # errors outright if anything is missing\nquantile(some_vector, probs = 0.25, na.rm = TRUE)   # works\n```\n:::\n\n\n::: callout-important\n## Knowing your gaps\n\nNotice the two different failure modes above: `mean()` fails\n*quietly* — it hands you back `NA` and lets you not notice — while\n`quantile()` fails *loudly*, with an error. The loud failure is the\nfriendlier one. The quiet one is how a wrong number ends up in a\nreport. Deciding what to do about missing data — ignore it, exclude\nthose rows, or fill it in — is a decision you must **make and\njustify**, not something to discover by accident halfway through a\nmodel.\n:::\n\n------------------------------------------------------------------------\n\n## What they're really asking for\n\nWe promised at the start of the chapter to come back to this, and it's\na key idea of this chapter.\n\nIn my experience, when someone asks for historical data, **they very\nrarely care about the past**. Attrition last year is over; nobody can\ndo anything about it. They want to look at the past because they are\ntrying to work out **what is going to happen next** — and whether they\nshould do something about it.\n\nThe request is descriptive. The question underneath it is predictive.\nAnd we hand over the description and let them do the hard part in\ntheir heads.\n\n### People are not good at this\n\nThat last step — looking at history and inferring the future — is one\nof the most thoroughly documented weaknesses in human judgement.\nDecades of research on decision-making under uncertainty finds the\nsame failures, and every one of them turns up monthly in HR reporting:\n\n-   **Small samples are trusted far too much.** Kahneman and Tversky\n    called this belief in the \"law of small numbers\": people expect a\n    small group to look like the population, so a 40% attrition figure\n    from a five-person team is read with roughly the confidence of a\n    figure from five hundred. Team-level dashboards are built almost\n    entirely from small samples.\n-   **Regression to the mean is mistaken for causation.** Extreme\n    results tend to be followed by less extreme ones, for no reason\n    other than arithmetic. So the worst-scoring team improves after\n    the intervention, the best-performing manager slips the following\n    year, and both movements get explained with a story. This is the\n    single most common way HR credits itself with an effect it didn't\n    have.\n-   **Noise is read as trend.** Two points make a line. Attrition ticks\n    from 11% to 13% and it becomes \"a worrying upward trend\" in the\n    commentary, when it's well within the wobble you'd see from a\n    stable process.\n-   **Confidence intervals are far too narrow.** When people are asked\n    for a range they're 90% sure about, the truth falls outside it\n    much more often than 10% of the time. We are systematically more\n    certain than we are right.\n-   **The story arrives before the evidence.** Give someone a chart and\n    a few seconds and they will produce a causal explanation for\n    whatever it shows — including, in experiments, for patterns that\n    were generated at random.\n\nNone of this is stupidity, and pointing it out to stakeholders doesn't\nhelp. These are the default settings of human intuition working on\nincomplete information, and analysts have them too.\n\n::: callout-important\n## Which is the actual argument for the rest of this book\n\nIf the inference is going to happen anyway, it's better done by a\nmethod than by a hunch.\n\nThat's what the following chapters are for. Rather than hand over a\nnumber and hope, you can present the data **and** a systematic\ninterpretation of it: an estimate, an honest range around that\nestimate, and where appropriate a forecast that already accounts for\nhow little data a small team really provides. The uncertainty gets\nquantified and shown rather than left to be misjudged.\n\nDo that, and you haven't just answered the question that was asked.\nYou've answered the one that was meant — and given HR, and the\nmanagers it serves, a genuinely better basis for a decision.\n:::\n\n------------------------------------------------------------------------\n\n## On the job {.unnumbered}\n\n::: callout-important\n## Why this matters day to day\n\nEvery People Analytics deliverable opens with a **description of the\ndata**: how many people, what the key variables look like, and where\nthe gaps are. Before anyone believes a model, they want to know you\nunderstand what you're working with — and a stakeholder who spots a\nheadcount that doesn't match theirs will not hear a word of the rest.\n\nTwo habits to take away today. **Check the gaps before you summarise\nanything**, because a quiet `NA` becomes a wrong number in a board\npack. And **ask what the request is for**, because the answer changes\nwhat you should send back.\n:::\n\n------------------------------------------------------------------------\n\n## Summary {.unnumbered}\n\n::: callout-note\n## Today you learned\n\n1.  **Exploratory data analysis** comes before everything: structure,\n    gaps, shapes, impossible values, and a sense-check against what\n    you know of the business.\n2.  A dataset is rows (observations) × columns (variables) with one\n    value per cell — **tidy data**. Analyse long, present wide.\n3.  Describe a **numeric** variable by its **centre** (mean, median)\n    and **spread** (SD, IQR); a gap between mean and median signals\n    skew. In HR that usually means **median for pay, tenure and\n    time-to-hire**.\n4.  Report **mean with SD**, or **median with IQR** — pair them\n    properly.\n5.  Describe a **categorical** variable with **counts** and\n    **proportions**.\n6.  **Histograms**, **boxplots** and **violin plots** picture numbers;\n    **bar charts** picture categories. Boxplots are for analysts;\n    violins travel better to managers, and neither shows the sample\n    size unless you add it.\n7.  **Check every column for missing values** before you summarise any\n    of them, and decide what to do about the gaps deliberately.\n8.  A request for **historical data is usually a question about the\n    future** — and human intuition handles that step badly. Supplying\n    the inference, with its uncertainty, is what the rest of this book\n    is for.\n9.  A 0/1 variable's **mean is a proportion** — our bridge to next\n    chapter.\n:::\n\n## Next chapter {.unnumbered}\n\n**Thinking in chances** — the first step towards supplying that\ninference rather than leaving it to intuition. We turn the promotion\nrate into a *probability*, and meet conditional probability: does the\nchance of promotion change once we know something else about the\nsalesperson?\n",
    "supporting": [
      "01-meeting-your-data_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}