{
  "hash": "6aeef8c3c48050cbcce426401df46f3b",
  "result": {
    "engine": "knitr",
    "markdown": "# Empirical Bayes: Estimating Rates You Don't Have Enough Data For\n\n## Welcome {.unnumbered}\n\nEvery People Analytics team eventually hits the same wall: you want to\ncompare a rate across a set of groups — offices, cohorts, teams,\nrecruiting channels — and some of those groups are tiny. A city office\nwith four managers, a recruiting channel that hired six people last\nquarter, a team of three. The raw rate for a small group swings wildly\non almost no evidence, and yet it's often the *extreme* small groups\nthat get the attention: the \"worst\" office, the \"best\" channel.\n\nThis chapter introduces **empirical Bayes** — a fast, elegant way to\nstabilise exactly these estimates, without needing to fit a full\nBayesian model. It's the technique behind a genuinely famous piece of\napplied statistics (estimating true batting averages in baseball from a\nsingle season), and it maps almost exactly onto People Analytics\nproblems.\n\n::: callout-important\nThe core idea in one sentence: **use the data itself to work out how\nmuch you should trust any one group's raw number, then pull the\nnoisiest estimates back toward the average by exactly that much.**\n:::\n\n## What you'll be able to do by the end {.unnumbered}\n\n1.  Explain why raw rates for small groups are systematically misleading\n2.  Estimate a prior distribution *from your own data* (the \"empirical\"\n    in empirical Bayes)\n3.  Combine that prior with each group's own data to get a stabilised\n    estimate\n4.  Know when to reach for empirical Bayes versus a full multilevel\n    model (Chapter 15)\n5.  Use an **external benchmark** as a prior when you don't have enough\n    of your own groups to estimate one reliably\n6.  Build a prior from **your own history**, and decide how much of that\n    history should still count\n\n------------------------------------------------------------------------\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(peopleanalyticsdata)\n\ntheme_set(theme_minimal(base_size = 13))\nset.seed(2026)\n\ndata(\"managers\", package = \"peopleanalyticsdata\")\n\n# Guard against missing values before grouping and estimating rates\n# (Chapter 1 found gaps in a similar teaching dataset).\nmanagers <- managers |> drop_na(concern_flag, city, high_hours_flag)\n```\n:::\n\n\nWe'll use the `managers` dataset: 571 managers, one row each, with a\n`concern_flag` (whether the manager has been the subject of a\ncomplaint), their `city`, and a handful of other characteristics. This\ndata — and every other dataset used in Part V of this book — comes from\nKeith McNulty's `peopleanalyticsdata` package; see the\n[Welcome](../index.qmd) chapter for the full credit.\n\n------------------------------------------------------------------------\n\n## The problem\n\n### A league table of cities\n\nSuppose you want to know: in which cities are managers more likely to\nhave a complaint filed against them? A natural first move — group by\ncity, compute the raw rate:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncity_rates <- managers |>\n  mutate(concern = if_else(concern_flag == \"Y\", 1, 0)) |>\n  group_by(city) |>\n  summarise(\n    n_managers = n(),\n    n_concerns = sum(concern),\n    raw_rate   = n_concerns / n_managers\n  ) |>\n  arrange(desc(raw_rate))\n\ncity_rates\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  city          n_managers n_concerns raw_rate\n  <fct>              <int>      <dbl>    <dbl>\n1 Orlando               23          4   0.174 \n2 Houston               25          4   0.16  \n3 New York             196         24   0.122 \n4 San Francisco         52          5   0.0962\n5 Toronto              213         16   0.0751\n6 Chicago               62          4   0.0645\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(city_rates, aes(x = n_managers, y = raw_rate)) +\n  geom_point(size = 2.5, colour = \"#122a52\") +\n  geom_hline(yintercept = mean(city_rates$n_concerns) / mean(city_rates$n_managers),\n             linetype = \"dashed\", colour = \"#d32f2f\") +\n  labs(\n    title = \"Raw complaint rate by city\",\n    subtitle = \"Dashed line = overall rate. Small offices swing to the extremes.\",\n    x = \"Number of managers in the city\", y = \"Raw complaint rate\"\n  )\n```\n\n::: {.cell-output-display}\n![](14-empirical-bayes_files/figure-html/raw-rates-plot-1.png){width=672}\n:::\n:::\n\n\n### Why this table is dangerous to publish as-is\n\nLook at where the highest and lowest rates sit: overwhelmingly among\nthe cities with the *fewest* managers. That's not a finding about those\ncities — it's arithmetic. With four managers, the only possible rates\nare 0%, 25%, 50%, 75% or 100%. A single complaint moves a small city\nfrom \"fine\" to \"an outlier\" instantly. A city with sixty managers\nbarely moves at all for the same one complaint.\n\n::: callout-important\nIf you rank cities by raw rate and act on the top and bottom of that\nlist, you are — mostly — ranking cities by **how little data you\nhave on them**, not by anything real about how they're managed.\n:::\n\nThis is exactly the same problem the multilevel-models chapter raised\nfor guest satisfaction and, in Chapter 15, for individual managers. It\nshows up everywhere in People Analytics because organisational units\nare almost never equally sized.\n\n------------------------------------------------------------------------\n\n## The empirical Bayes idea\n\n### Start from Bayes' theorem, as before\n\nFor any one city, if we treat each manager as a coin flip with an\nunknown \"true\" concern rate $\\theta$, Bayes' theorem says:\n\n$$\n\\text{posterior rate} \\propto \\text{prior} \\times \\text{likelihood (the city's own data)}\n$$\n\nThe Beta-Binomial model from Chapter 4 gives us a clean way to do this:\nif the prior is $\\text{Beta}(\\alpha, \\beta)$ and a city has $n$ managers\nwith $k$ concerns, the posterior is $\\text{Beta}(\\alpha + k, \\beta + n -\nk)$, and its mean is:\n\n$$\n\\hat\\theta = \\frac{\\alpha + k}{\\alpha + \\beta + n}\n$$\n\nRead that formula carefully: $\\alpha$ and $\\beta$ act like **extra,\nimaginary managers** added to every city — $\\alpha$ imaginary concerns\nand $\\beta$ imaginary clean records. A small city's real data gets\noutweighed by these imaginary managers; a large city's real data\nswamps them. That's the shrinkage mechanism, in one formula.\n\n### The empirical Bayes shortcut\n\nIn Chapter 4 you had to *choose* a prior. Empirical Bayes instead asks:\n**what single Beta distribution best describes the spread of raw rates\nwe actually observed across all our cities?** We estimate $\\alpha$ and\n$\\beta$ directly from the vector of city-level rates, using a simple\nmethod-of-moments fit:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu    <- mean(city_rates$raw_rate)\nvar_r <- var(city_rates$raw_rate)\n\n# Method-of-moments Beta parameters\nalpha0 <- mu * ((mu * (1 - mu) / var_r) - 1)\nbeta0  <- (1 - mu) * ((mu * (1 - mu) / var_r) - 1)\n\ntibble(alpha0, beta0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  alpha0 beta0\n   <dbl> <dbl>\n1   5.74  44.1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(theta = seq(0, 0.6, length.out = 400)) |>\n  mutate(density = dbeta(theta, alpha0, beta0)) |>\n  ggplot(aes(theta, density)) +\n  geom_line(colour = \"#122a52\", linewidth = 1) +\n  geom_vline(xintercept = mu, linetype = \"dashed\", colour = \"#d32f2f\") +\n  labs(\n    title = \"The empirically estimated prior\",\n    subtitle = \"Estimated from the spread of raw city rates itself\",\n    x = expression(theta~\"(true concern rate)\"), y = \"Density\"\n  )\n```\n\n::: {.cell-output-display}\n![](14-empirical-bayes_files/figure-html/prior-plot-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n## A different lens: frequentist statistics has a version of this too\n\nIf your background is frequentist statistics, this might feel like it\ncomes out of nowhere — but it doesn't. In the 1960s, Charles Stein\nproved something that shocked the statistics world: if you want to\nestimate several unrelated quantities at once (say, the true rate for\neach of our cities), you get *better overall accuracy* by pulling every\nestimate a little toward the grand average — even when the quantities\nhave nothing to do with each other. This became known as **Stein's\nparadox**, and the **James-Stein estimator** is its practical form.\nEmpirical Bayes is the natural route to the same destination from a\nBayesian starting point: same shrinkage, same reasoning about small\nsamples, arrived at via a prior instead of a minimax argument. It's not\na fringe Bayesian trick — it's a well-established result that classical\nand Bayesian statistics converge on independently.\n:::\n\n::: callout-tip\n## For the ML/DS crowd\n\nIf you've ever tuned an L1 or L2 regularisation strength via\ncross-validation, you've already done something very close to this by\nhand. A ridge-regression penalty is mathematically equivalent to\nputting a Normal prior on your coefficients; the penalty strength is\nequivalent to that prior's precision. Cross-validating the penalty is\nchoosing the prior's strength empirically by trial and error over held-out\ndata. Empirical Bayes just estimates that strength directly from the\ndata's own spread, in closed form, without a validation loop. Same\ninstinct — \"let the data tell you how much to trust extreme values\" —\ndifferent mechanics.\n\n(One disambiguation while we're here: **empirical Bayes has nothing to\ndo with a \"naive Bayes classifier.\"** They share a name and a theorem,\nnot much else — naive Bayes is a classification algorithm that assumes\nfeature independence; empirical Bayes is a way of estimating priors\nfrom data. Easy to conflate on a first pass.)\n:::\n\n::: callout-note\n## Why this is a slightly uncomfortable idea, and why it's fine anyway\n\nUsing the data to build the prior *and* then using the same data again\nin the likelihood sounds circular — full Bayesians will point this out.\nIn practice it works extremely well as an approximation to a full\nhierarchical model (Chapter 15 fits the \"proper\" version and you'll see\nthe answers are very close), and it has one big advantage: **no MCMC,\nanswers in milliseconds.** Treat it as a fast, practical tool — not a\nsubstitute for a full model when the stakes are high enough to justify\none.\n:::\n\n### Apply it to every city\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncity_eb <- city_rates |>\n  mutate(\n    eb_rate = (alpha0 + n_concerns) / (alpha0 + beta0 + n_managers)\n  ) |>\n  arrange(desc(eb_rate))\n\ncity_eb\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  city          n_managers n_concerns raw_rate eb_rate\n  <fct>              <int>      <dbl>    <dbl>   <dbl>\n1 Orlando               23          4   0.174   0.134 \n2 Houston               25          4   0.16    0.130 \n3 New York             196         24   0.122   0.121 \n4 San Francisco         52          5   0.0962  0.106 \n5 Chicago               62          4   0.0645  0.0872\n6 Toronto              213         16   0.0751  0.0827\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(city_eb, aes(x = n_managers)) +\n  geom_hline(yintercept = mu, linetype = \"dashed\", colour = \"#d32f2f\") +\n  geom_segment(aes(xend = n_managers, y = raw_rate, yend = eb_rate),\n               colour = \"grey80\") +\n  geom_point(aes(y = raw_rate), colour = \"grey70\", size = 2.5) +\n  geom_point(aes(y = eb_rate), colour = \"#122a52\", size = 2.5) +\n  scale_x_log10() +\n  labs(\n    title = \"Empirical Bayes pulls small cities toward the overall rate\",\n    subtitle = \"Grey = raw rate, navy = empirical Bayes estimate, red dashed = overall rate\",\n    x = \"Number of managers (log scale)\", y = \"Concern rate\"\n  )\n```\n\n::: {.cell-output-display}\n![](14-empirical-bayes_files/figure-html/eb-shrinkage-plot-1.png){width=672}\n:::\n:::\n\n\nRead this the same way you read the shrinkage plot in Chapter 8: small\noffices move a long way, large ones barely move, and nobody had to pick\na threshold for \"too small to trust.\"\n\n::: callout-caution\n## Try it yourself\n\nRecompute this with `high_hours_flag` instead of `concern_flag`. Does\nthe ranking of cities change much once you apply empirical Bayes? Which\ncities were \"extreme\" on the raw rate but unremarkable once shrunk?\n:::\n\n------------------------------------------------------------------------\n\n## Using external benchmarks as priors\n\nEmpirical Bayes needs *enough groups* to estimate a sensible prior. If\nyour organisation has five offices, estimating a Beta distribution from\nfive raw rates is itself unreliable — you'd be building a shaky prior\nout of shaky ingredients.\n\nA common, entirely legitimate alternative: build your prior from an\n**external benchmark** instead of your own groups.\n\n::: callout-note\n## A worked (illustrative) example\n\nSuppose your industry body publishes an average annual voluntary\nattrition rate of 14%, based on a large cross-industry survey, and you\nhave no strong reason to think your organisation differs systematically\nfrom that average *before* looking at your own data. You could encode\nthat as a prior:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# A Beta prior centred on 14%, with moderate confidence\n# (equivalent to having already observed ~50 \"imaginary\" employees\n#  at that rate before seeing any of your own data)\nbenchmark_rate <- 0.14\nprior_strength <- 50\n\nalpha_bench <- benchmark_rate * prior_strength\nbeta_bench  <- (1 - benchmark_rate) * prior_strength\n\ntibble(alpha_bench, beta_bench)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  alpha_bench beta_bench\n        <dbl>      <dbl>\n1           7         43\n```\n\n\n:::\n:::\n\n\nSame habit as everywhere else in this book — look at it before using it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(theta = seq(0, 0.5, length.out = 400)) |>\n  mutate(density = dbeta(theta, alpha_bench, beta_bench)) |>\n  ggplot(aes(theta, density)) +\n  geom_area(fill = \"#122a52\", alpha = 0.5) +\n  geom_vline(xintercept = benchmark_rate, linetype = \"dashed\", colour = \"#d32f2f\") +\n  labs(\n    title = \"The benchmark-derived prior: Beta(7, 43)\",\n    subtitle = \"Centred on the industry's 14% rate, moderately confident\",\n    x = \"Attrition rate\", y = \"Prior density\"\n  )\n```\n\n::: {.cell-output-display}\n![](14-empirical-bayes_files/figure-html/plot-benchmark-prior-1.png){width=672}\n:::\n:::\n\n\nNow combine it with, say, a 30-person team that has had 2 departures\nthis year:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_team <- 30\nk_team <- 2\n\nposterior_mean <- (alpha_bench + k_team) / (alpha_bench + beta_bench + n_team)\nraw_rate_team  <- k_team / n_team\n\ntibble(raw_rate_team, posterior_mean, benchmark_rate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  raw_rate_team posterior_mean benchmark_rate\n          <dbl>          <dbl>          <dbl>\n1        0.0667          0.112           0.14\n```\n\n\n:::\n:::\n\n:::\n\nNotice what happened: the raw rate (6.7%) looks dramatically better\nthan the industry benchmark, but with only 30 people that's thin\nevidence — the posterior estimate sits between the raw rate and the\nbenchmark, appropriately hedging until more of your own data arrives.\n\n::: callout-important\n## The knob that matters: `prior_strength`\n\n`prior_strength` (the $\\alpha + \\beta$ total) is doing all the work of\nsaying *\"how much should the benchmark count for, relative to a single\nemployee's worth of your own data?\"* Setting it too high means your own\ndata can never move the estimate; too low and the benchmark barely\nmatters. There's no universal right answer — state your choice\nexplicitly and, ideally, show how sensitive the conclusion is to it (a\nprior sensitivity check, exactly as in Chapter 5).\n:::\n\n------------------------------------------------------------------------\n\n## Priors from your own past\n\nSo far this chapter has built a prior two ways: from the spread across\nyour own groups, and from an external benchmark. There's a third\nsource sitting right there in your HRIS, and it's usually the most\npersuasive one in a meeting — **your own history**. You have last\nyear's promotion rates, the last three years of attrition, eight\nquarters of offer acceptances. Chapter 4 showed the mechanism already:\ntoday's posterior is tomorrow's prior, so history rolls forward on its\nown.\n\nIt also came with a warning, which is what this section is about.\nRolling history forward assumes the process that generated it is the\nsame process running today. Organisations violate that assumption\nconstantly — a reorganisation, a new promotion policy, a change of\nleadership, a hiring freeze. When that happens, evidence from three\nyears ago describes a process that no longer exists, and the more of\nit you have the more confidently wrong it makes you.\n\nSo the question isn't whether to use your history. It's **how much of\nit still counts.**\n\n### First ask: did it change gradually, or all at once?\n\nThis is the whole decision, and it's not a statistical one. You answer\nit by knowing your organisation.\n\nMost of the changes People Analytics deals with are **step changes**.\nThe reorganisation happened in March. The new promotion framework\nlaunched in Q2. The bands were rebuilt on the first of January. There\nis a date, people remember it, and the process genuinely is different\neither side of it.\n\n::: callout-important\n## When there's a date, cut — don't decay\n\nIf you can name the month it changed, the honest move is to **use only\nthe data since then**, and say so in one sentence: *\"this uses\npromotions from April onward, because the framework changed in\nMarch.\"*\n\nThat's defensible to anyone in the room, it needs no method, and it\nsurvives being challenged. A decay curve applied to a step change is\nworse on both counts — it still lets pre-change data influence the\nanswer, and it obscures a clean editorial decision behind machinery.\n\nThe instinct to reach for the sophisticated tool is strong here, and\nit's usually wrong. The crude one is more defensible.\n:::\n\nThe cost of cutting is obvious: you throw data away, and if the change\nwas recent you may have very little left. That's not a reason to keep\nthe old data — it's a reason to be honest that you're now in a\nsmall-sample situation, which is what the rest of this chapter is for.\n\n**Gradual drift** is the other case, and it's rarer than it feels.\nNothing changed on a particular Tuesday; the organisation has simply\nbeen getting steadily younger, or the labour market has been slowly\nloosening, and evidence from four years ago is less relevant than\nevidence from last quarter without there being a line to draw. That's\nwhere decay earns its place.\n\n### Decay weighting, in the same closed form\n\nThe mechanic is a small extension of what you've already done. Instead\nof counting every historical observation once, count each one by a\nweight that falls off with age:\n\n$$\nw = \\tfrac{1}{2}^{\\,\\text{age} / h}\n$$\n\nwhere $h$ is a **half-life** — the age at which an observation counts\nfor half of a fresh one. Then build the prior from the weighted counts\nrather than the raw ones.\n\n::: callout-note\n## A worked (illustrative) example\n\nEight quarters of promotion history, oldest first — the kind of table\nyou'd assemble from an HRIS extract:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhistory <- tibble(\n  quarter    = 1:8,\n  eligible   = c(52, 48, 61, 55, 44, 58, 50, 47),\n  promoted   = c(19, 17, 21, 17, 12, 15, 12, 11)\n) |>\n  mutate(quarters_ago = max(quarter) - quarter)\n\nhistory\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 4\n  quarter eligible promoted quarters_ago\n    <int>    <dbl>    <dbl>        <int>\n1       1       52       19            7\n2       2       48       17            6\n3       3       61       21            5\n4       4       55       17            4\n5       5       44       12            3\n6       6       58       15            2\n7       7       50       12            1\n8       8       47       11            0\n```\n\n\n:::\n:::\n\n\nPick a half-life and compute the weights. With a four-quarter\nhalf-life, the oldest quarter here counts for about a third of the\nmost recent one:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhalf_life <- 4                                                    # <1>\n\nhistory <- history |>\n  mutate(weight = 0.5 ^ (quarters_ago / half_life))\n\nhistory |> select(quarters_ago, eligible, promoted, weight)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 4\n  quarters_ago eligible promoted weight\n         <int>    <dbl>    <dbl>  <dbl>\n1            7       52       19  0.297\n2            6       48       17  0.354\n3            5       61       21  0.420\n4            4       55       17  0.5  \n5            3       44       12  0.595\n6            2       58       15  0.707\n7            1       50       12  0.841\n8            0       47       11  1    \n```\n\n\n:::\n:::\n\n\n1.  In quarters, matching the unit of `quarters_ago`. This is the one\n    genuine judgement call in the section — see the callout below.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(history, aes(x = quarters_ago, y = weight)) +\n  geom_col(fill = \"#122a52\", alpha = 0.45, width = 0.7) +\n  scale_x_reverse() +\n  labs(\n    title = \"How much each quarter still counts\",\n    subtitle = \"Four-quarter half-life: a year ago counts for half, two years ago a quarter\",\n    x = \"Quarters ago\", y = \"Weight\"\n  )\n```\n\n::: {.cell-output-display}\n![](14-empirical-bayes_files/figure-html/decay-weight-plot-1.png){width=672}\n:::\n:::\n\n\nNow the prior. The Beta-Binomial update from Chapter 4 said *add your\nsuccesses to* $\\alpha$ *and your failures to* $\\beta$. Here we add the\n**weighted** successes and failures instead:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha_hist <- sum(history$weight * history$promoted)\nbeta_hist  <- sum(history$weight * (history$eligible - history$promoted))\n\nn_raw <- sum(history$eligible)\nn_eff <- alpha_hist + beta_hist                                   # <1>\n\ntibble(alpha_hist, beta_hist, n_raw, n_eff)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  alpha_hist beta_hist n_raw n_eff\n       <dbl>     <dbl> <dbl> <dbl>\n1       67.8      174.   415  242.\n```\n\n\n:::\n:::\n\n\n1.  $\\alpha + \\beta$ is the prior's strength in units of people —\n    the same knob as `prior_strength` in the benchmark section, except\n    here you didn't choose it directly, the decay chose it for you.\n\nThat last number is the one to report. You have 415\nhistorical observations and roughly 242 observations'\n*worth* of evidence, because you've decided the old ones count for\nless. Both numbers are true; only the second one is being used.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheta <- seq(0, 0.7, length.out = 400)\n\nalpha_flat <- sum(history$promoted)\nbeta_flat  <- sum(history$eligible - history$promoted)\n\ntibble(\n  theta,\n  `all history, counted equally` = dbeta(theta, alpha_flat, beta_flat),\n  `discounted by age`            = dbeta(theta, alpha_hist, beta_hist)\n) |>\n  pivot_longer(-theta, names_to = \"prior\", values_to = \"density\") |>\n  ggplot(aes(theta, density, colour = prior)) +\n  geom_line(linewidth = 1) +\n  scale_colour_manual(values = c(\"grey70\", \"#8fabd0\")) +\n  labs(\n    title = \"Discounting the past widens the prior — and moves it\",\n    subtitle = \"Promotion rate has been drifting down; the discounted prior follows it\",\n    x = expression(theta~\"(true promotion rate)\"), y = \"Prior density\",\n    colour = NULL\n  )\n```\n\n::: {.cell-output-display}\n![](14-empirical-bayes_files/figure-html/decay-prior-plot-1.png){width=672}\n:::\n:::\n\n:::\n\nTwo things happen at once there, and both are the point. The\ndiscounted prior is **wider**, because you're honestly claiming less\nevidence than you physically hold. And it has **moved**, tracking the\nrecent quarters rather than averaging across a drift. A prior that\ncounted all eight quarters equally would be narrower *and* centred in\nthe wrong place — the worst combination available.\n\n::: callout-important\n## Choosing the half-life\n\nThere is no data-driven answer, and you should be suspicious of anyone\nwho offers you one. The half-life is a statement about your\norganisation: *how long does it take for the way we promote people to\nstop resembling the way we promoted them then?*\n\nTwo rules make it defensible. **State it, in plain words** — \"evidence\nfrom two years ago counts for a quarter of evidence from this quarter\"\nis a sentence a stakeholder can push back on, and $h = 4$ isn't. And\n**show what it costs you**: refit with a half-life half as long and\ntwice as long, and report whether the conclusion changes. If it does,\nthat sensitivity *is* the finding, and the honest answer is that you\ndon't have enough recent data to settle the question.\n\nSame discipline as the prior sensitivity check in Chapter 5. Same\nreason.\n:::\n\nIf you're modelling rather than counting rates, the same idea arrives\nas a `weights =` argument in `brm()` — one weight per row, computed\nexactly as above. That's the one place in this book where the `brm()`\nskeleton gains an argument, and it's worth the exception: that single\nargument is where \"how much should the past count?\" lives.\n\n### Names worth knowing, and where to stop\n\nEverything above is deliberately the cheap version. There is a\nsubstantial literature underneath it, and the useful thing at this\npoint isn't a worked example of each — it's knowing what to search\nfor when your problem outgrows a half-life:\n\n-   **Power priors** — the formal version of what we just did: raise\n    the historical likelihood to a power between 0 and 1 to discount\n    it. The literature covers how to choose that power, including\n    letting the model estimate it.\n-   **Change-point models** — for when you're fairly sure something\n    shifted but can't name the date. The model finds it, and gives you\n    a posterior over *when* rather than making you pick.\n-   **State-space and dynamic linear models** — θ becomes something\n    that moves, with its own model for how fast it's allowed to move.\n    The proper answer to genuine drift, and a different way of working\n    rather than an extra argument.\n-   **Time-varying effects in `brms`** — `s(time)` or `gp(time)` in a\n    model formula, letting a rate or a coefficient bend smoothly over\n    time without leaving tools you already know.\n\n::: callout-note\nThe reason to name these without expanding them is that the hardest\npart of the problem is usually knowing that a solution exists and what\nit's called. If you've read this far you can recognise the situation —\nyour history is real but stale, and a single number for \"the rate\" is\nhiding a moving target. That recognition is most of the work. The\nsearch terms are the rest.\n:::\n\n------------------------------------------------------------------------\n\n### The workflow steps this chapter skips, and why\n\nChapter 10's workflow assumes you fitted a model. Most of this chapter\ndoes not, and it is worth being explicit rather than leaving the gap\nlooking like carelessness.\n\nEmpirical Bayes here is **closed-form arithmetic**, not sampling. There\nare no chains to diagnose (step 7) because nothing was sampled, and no\nposterior predictive check (step 8) in the usual sense because there is\nno generative model to simulate from — the Beta prior was estimated from\nthe group rates by method of moments, and the update is a formula.\n\nWhat replaces them is the comparison in the next section: fit the full\nmultilevel model and check the two answers agree. **That is the check.**\nIf the closed-form shortcut and the properly-fitted model disagree, the\ndistributional assumption behind the shortcut is wrong, and you have\nfound out in the only way available.\n\nThe steps that do still apply, and are not optional: know what you are\nclaiming (step 2 — these are descriptions of groups, not effects of\nbeing in one), and temper the result (step 10 — a shrunk rate is still\nbuilt on a raw count that may itself be noisy).\n\n------------------------------------------------------------------------\n\n## Empirical Bayes vs. a full multilevel model\n\n| | **Empirical Bayes (this chapter)** | **Multilevel model (Ch. 8, 14)** |\n|---|---|---|\n| Speed | Instant, closed-form | Seconds to minutes (MCMC) |\n| Uncertainty | Point estimate only, by default | Full posterior for every group |\n| Assumes | A single, simple distributional shape for the prior | Whatever you specify — more flexible |\n| Good for | A quick first look, dashboards, many repeated similar analyses | The version you'd defend to a sceptical stakeholder or publish |\n\nNeither is \"more correct\" in every situation. A sensible default:\nprototype with empirical Bayes because it's instant, then confirm the\nconclusion holds with a proper multilevel model before you act on it —\nwhich is exactly what Chapter 15 does, on a closely related problem.\n\n------------------------------------------------------------------------\n\n## On the job {.unnumbered}\n\n::: callout-important\n## Why this matters day to day\n\nAlmost every People Analytics deliverable involves ranking or comparing\ngroups of unequal size: offices, recruiting channels, onboarding\ncohorts, manager populations. Empirical Bayes is the fastest tool in\nthis book for stopping a stakeholder from over-reacting to the office\nwith four people and one bad month. It costs you one extra line of R\nand no modelling framework — there's rarely a reason *not* to check a\nraw rate this way before it goes in a deck.\n:::\n\n------------------------------------------------------------------------\n\n## Summary {.unnumbered}\n\n::: callout-note\n## Today you learned\n\n1.  Raw rates for small groups are noisy in a *predictable* direction —\n    they produce the most extreme values.\n2.  Empirical Bayes estimates the prior **from the spread of your own\n    groups' rates**, then shrinks each group toward it in closed form.\n3.  The shrinkage amount is set automatically by how much groups\n    genuinely differ versus how much is just noise.\n4.  When you don't have enough groups of your own, an **external\n    benchmark** can play the same role as the prior — with an explicit,\n    checkable choice of how strongly to weight it.\n5.  **Your own history** is the third source of a prior, and the only\n    one that needs an expiry date. If you can name the month the\n    process changed, cut the data there and say so. If it drifted\n    instead, discount older observations by a stated half-life and\n    report the effective sample size you're left with.\n6.  Empirical Bayes is a fast approximation to the full multilevel\n    model in the next chapter — prototype with one, confirm with the\n    other.\n:::\n\n## Next chapter {.unnumbered}\n\n**Bayesian shrinkage: ranking managers and teams fairly** — we take this\nexact idea and apply it properly, with a full Bayesian model, to the\nquestion that probably brought you to this chapter: which managers are\ngenuinely better or worse, once you account for team size?\n",
    "supporting": [
      "14-empirical-bayes_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}