<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>20&nbsp; Bayesian A/B Testing for People Experiments – Bayesian Thinking for People Analytics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/21-causal-structure-dags.html" rel="next">
<link href="../chapters/19-measurement-error-missing-data.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-5fd49111c67786fa9da7eec5f8b0b01d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-d674355c35ba9b8500a9db5196442da3.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Bayesian Thinking for People Analytics</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-wide tools-end">
    <a href="https://github.com/Andrew-Marritt/hr-bayes-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/14-empirical-bayes.html">People Analytics deep dives</a></li><li class="breadcrumb-item"><a href="../chapters/20-bayesian-ab-testing.html"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Bayesian A/B Testing for People Experiments</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-meeting-your-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Meeting Your Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-thinking-in-chances.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Thinking in Chances</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-distributions-sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Distributions, Sampling &amp; the Idea of a Model</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Bayesian core</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-bayes-theorem.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Bayesian Thinking: Bayes' Theorem &amp; Your First Inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-posteriors-priors-credible-intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Posteriors, Priors &amp; Credible Intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-bayesian-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Bayesian Regression: Explaining &amp; Predicting</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Applied workflow</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-groups-and-categories.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Groups &amp; Categories: Comparing and Choosing Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-multilevel-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">When Data Has Structure: Multilevel Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-logistic-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Logistic Regression: Modelling a Yes/No Outcome</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-complete-workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">The Complete Workflow: From Question to Recommendation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Going further</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-mcmc-under-the-hood.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Inside the Sampler: MCMC &amp; Trustworthy Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12-richer-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Richer Models: When the Standard Recipe Runs Out</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/13-model-building-craft.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Model Building as Craft: The Decisions Software Won’t Make For You</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">People Analytics deep dives</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/14-empirical-bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Empirical Bayes: Estimating Rates You Don’t Have Enough Data For</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/15-bayesian-shrinkage-managers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Bayesian Shrinkage: Ranking Managers and Teams Fairly</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/16-hierarchical-pay-variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Hierarchical Models for Pay and Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/17-survival-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Survival Analysis: Time-to-Event in the Employee Lifecycle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/18-likert-survey-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Analysing Likert and Survey Data the Bayesian Way</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/19-measurement-error-missing-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Modelling What You Can't See: Measurement Error, Missing Data &amp; Latent Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/20-bayesian-ab-testing.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Bayesian A/B Testing for People Experiments</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/21-causal-structure-dags.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Causal Structure: Drawing the Graph</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/22-causal-designs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Causal Designs: Finding Variation You Didn’t Create</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/23-elicitation-workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">The Elicitation Workflow: Building Priors With Your Stakeholders</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">From analysis to decision</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/24-posterior-to-decision.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">From Posterior to Decision: What an Analysis Is Worth</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/A0-getting-started-with-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Getting started with R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/A1-llms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Using LLMs for analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/A2-further-reading.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Further reading</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/A3-data-sources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Data sources</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#welcome-back" id="toc-welcome-back" class="nav-link active" data-scroll-target="#welcome-back">Welcome back</a></li>
  <li><a href="#what-youll-be-able-to-do-by-the-end" id="toc-what-youll-be-able-to-do-by-the-end" class="nav-link" data-scroll-target="#what-youll-be-able-to-do-by-the-end">What you’ll be able to do by the end</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup"><span class="header-section-number">20.1</span> Setup</a></li>
  <li><a href="#the-question" id="toc-the-question" class="nav-link" data-scroll-target="#the-question"><span class="header-section-number">20.2</span> The question</a></li>
  <li><a href="#the-bayesian-ab-test" id="toc-the-bayesian-ab-test" class="nav-link" data-scroll-target="#the-bayesian-ab-test"><span class="header-section-number">20.3</span> The Bayesian A/B test</a>
  <ul class="collapse">
  <li><a href="#one-posterior-per-group" id="toc-one-posterior-per-group" class="nav-link" data-scroll-target="#one-posterior-per-group"><span class="header-section-number">20.3.1</span> One posterior per group</a></li>
  <li><a href="#the-question-a-p-value-doesnt-answer-directly-pa-beats-b" id="toc-the-question-a-p-value-doesnt-answer-directly-pa-beats-b" class="nav-link" data-scroll-target="#the-question-a-p-value-doesnt-answer-directly-pa-beats-b"><span class="header-section-number">20.3.2</span> The question a p-value doesn’t answer directly: P(A beats B)</a></li>
  </ul></li>
  <li><a href="#is-the-difference-big-enough-to-act-on" id="toc-is-the-difference-big-enough-to-act-on" class="nav-link" data-scroll-target="#is-the-difference-big-enough-to-act-on"><span class="header-section-number">20.4</span> Is the difference big enough to act on?</a></li>
  <li><a href="#how-this-compares-to-other-approaches" id="toc-how-this-compares-to-other-approaches" class="nav-link" data-scroll-target="#how-this-compares-to-other-approaches"><span class="header-section-number">20.5</span> How this compares to other approaches</a></li>
  <li><a href="#on-the-job" id="toc-on-the-job" class="nav-link" data-scroll-target="#on-the-job">On the job</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#next-chapter" id="toc-next-chapter" class="nav-link" data-scroll-target="#next-chapter">Next chapter</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/14-empirical-bayes.html">People Analytics deep dives</a></li><li class="breadcrumb-item"><a href="../chapters/20-bayesian-ab-testing.html"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Bayesian A/B Testing for People Experiments</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Bayesian A/B Testing for People Experiments</span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="welcome-back" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="welcome-back">Welcome back</h2>
<p>People Analytics runs experiments constantly, even when nobody calls them that: did the new interview process change the hire rate, did the flexible-work pilot change retention, does one group’s promotion rate genuinely differ from another’s. Unlike a web A/B test with millions of visitors overnight, these experiments usually have <strong>dozens or hundreds</strong> of people in each group, and the answer is needed for a decision, not a p-value.</p>
<p>This chapter builds a Bayesian A/B test from the same Beta-Binomial machinery you met in Chapter 4, and shows why its output — “there’s an 87% chance A beats B, and if it does, it’s probably by 2–9 points” — is usually a better fit for a People Analytics decision than a significance test.</p>
</section>
<section id="what-youll-be-able-to-do-by-the-end" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="what-youll-be-able-to-do-by-the-end">What you’ll be able to do by the end</h2>
<ol type="1">
<li>Set up a Bayesian A/B test for two groups’ rates using Beta posteriors</li>
<li>Compute <strong>P(A beats B)</strong> directly from posterior samples</li>
<li>Report the size of a likely difference, not just its direction</li>
<li>Compare this to a classical proportions test and to Bayes-Factor hypothesis testing, and know when each is the better tool</li>
<li>Apply appropriate care when the “test” involves a protected characteristic</li>
</ol>
<hr>
</section>
<section id="setup" class="level2" data-number="20.1">
<h2 data-number="20.1" class="anchored" data-anchor-id="setup"><span class="header-section-number">20.1</span> Setup</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(peopleanalyticsdata)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>))</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Shared colour tokens (matching theme/academicdesign*.scss). Navy and light</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># navy carry the data; red is reserved for reference lines and annotations,</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># never for a second data series.</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>navy       <span class="ot">&lt;-</span> <span class="st">"#122a52"</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>navy_light <span class="ot">&lt;-</span> <span class="st">"#8fabd0"</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>red        <span class="ot">&lt;-</span> <span class="st">"#d32f2f"</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"promotion"</span>, <span class="at">package =</span> <span class="st">"peopleanalyticsdata"</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Guard against missing values before grouping and modelling (Chapter 1</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># found gaps in a similar teaching dataset).</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>promotion <span class="ot">&lt;-</span> promotion <span class="sc">|&gt;</span> <span class="fu">drop_na</span>(diverse, flexible, store, promoted)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>promotion</code> has 1,134 employee records from a retail company: <code>diverse</code> (membership of a diversity group at the company), <code>flexible</code> (worked part-time for 6+ months), <code>store</code> (joined working in retail stores), and <code>promoted</code> (the outcome).</p>
<hr>
</section>
<section id="the-question" class="level2" data-number="20.2">
<h2 data-number="20.2" class="anchored" data-anchor-id="the-question"><span class="header-section-number">20.2</span> The question</h2>
<p>Promotion-rate comparisons between groups are one of the most common — and most consequential — comparisons a People Analytics team is asked to make, often as part of routine equity monitoring. We’ll use it as our worked example:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="annotated-cell-2"><pre class="sourceCode r code-annotation-code code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-2-1"><a href="#annotated-cell-2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># `diverse` may be coded as Y/N or 1/0 depending on data version — normalise</span></span>
<span id="annotated-cell-2-2"><a href="#annotated-cell-2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># to an explicit, readable label so every downstream step is unambiguous.</span></span>
<span id="annotated-cell-2-3"><a href="#annotated-cell-2-3" aria-hidden="true" tabindex="-1"></a>promotion <span class="ot">&lt;-</span> promotion <span class="sc">|&gt;</span></span>
<span id="annotated-cell-2-4"><a href="#annotated-cell-2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">diverse_grp =</span> <span class="fu">if_else</span>(diverse <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Y"</span>, <span class="st">"1"</span>, <span class="dv">1</span>, <span class="cn">TRUE</span>),</span>
<span id="annotated-cell-2-5"><a href="#annotated-cell-2-5" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"diverse_group"</span>, <span class="st">"comparison_group"</span>))</span>
<span id="annotated-cell-2-6"><a href="#annotated-cell-2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-2-7"><a href="#annotated-cell-2-7" aria-hidden="true" tabindex="-1"></a>group_rates <span class="ot">&lt;-</span> promotion <span class="sc">|&gt;</span></span>
<span id="annotated-cell-2-8"><a href="#annotated-cell-2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(diverse_grp) <span class="sc">|&gt;</span></span>
<span id="annotated-cell-2-9"><a href="#annotated-cell-2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="annotated-cell-2-10"><a href="#annotated-cell-2-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="annotated-cell-2-11"><a href="#annotated-cell-2-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">promoted_n =</span> <span class="fu">sum</span>(promoted <span class="sc">==</span> <span class="dv">1</span> <span class="sc">|</span> promoted <span class="sc">==</span> <span class="st">"Y"</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="annotated-cell-2-12"><a href="#annotated-cell-2-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">raw_rate =</span> promoted_n <span class="sc">/</span> n</span>
<span id="annotated-cell-2-13"><a href="#annotated-cell-2-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="annotated-cell-2-14"><a href="#annotated-cell-2-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">label =</span> <span class="fu">if_else</span>(diverse_grp <span class="sc">==</span> <span class="st">"diverse_group"</span>,</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-2" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-2-15" class="code-annotation-target"><a href="#annotated-cell-2-15" aria-hidden="true" tabindex="-1"></a>                         <span class="st">"Diversity group"</span>, <span class="st">"Comparison group"</span>))</span>
<span id="annotated-cell-2-16"><a href="#annotated-cell-2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-2-17"><a href="#annotated-cell-2-17" aria-hidden="true" tabindex="-1"></a>group_rates</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-2" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-2" data-code-lines="15" data-code-annotation="1">A presentation-ready label alongside the raw coding. Legends and axis labels in this book never show a raw variable value — <code>diverse_grp</code> is for the code, <code>label</code> is for the reader.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  diverse_grp          n promoted_n raw_rate label           
  &lt;chr&gt;            &lt;int&gt;      &lt;int&gt;    &lt;dbl&gt; &lt;chr&gt;           
1 comparison_group   701        152   0.217  Comparison group
2 diverse_group      433         31   0.0716 Diversity group </code></pre>
</div>
</div>
<p>Describe it, then plot it — Chapter 10’s step 2, and worth doing even when the data is only four numbers, because the plot is where the sample sizes become visible:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="annotated-cell-3"><pre class="sourceCode r code-annotation-code code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-3-1"><a href="#annotated-cell-3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(group_rates, <span class="fu">aes</span>(<span class="at">x =</span> raw_rate, <span class="at">y =</span> <span class="fu">fct_rev</span>(label))) <span class="sc">+</span></span>
<span id="annotated-cell-3-2"><a href="#annotated-cell-3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> navy_light, <span class="at">colour =</span> navy, <span class="at">width =</span> <span class="fl">0.55</span>) <span class="sc">+</span></span>
<span id="annotated-cell-3-3"><a href="#annotated-cell-3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">weighted.mean</span>(group_rates<span class="sc">$</span>raw_rate, group_rates<span class="sc">$</span>n),</span>
<span id="annotated-cell-3-4"><a href="#annotated-cell-3-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> red) <span class="sc">+</span></span>
<span id="annotated-cell-3-5"><a href="#annotated-cell-3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(promoted_n, <span class="st">" of "</span>, n)),</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-3" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-3-6" class="code-annotation-target"><a href="#annotated-cell-3-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.15</span>, <span class="at">size =</span> <span class="fl">3.4</span>, <span class="at">colour =</span> navy) <span class="sc">+</span></span>
<span id="annotated-cell-3-7"><a href="#annotated-cell-3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent,</span>
<span id="annotated-cell-3-8"><a href="#annotated-cell-3-8" aria-hidden="true" tabindex="-1"></a>                     <span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.25</span>))) <span class="sc">+</span></span>
<span id="annotated-cell-3-9"><a href="#annotated-cell-3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="annotated-cell-3-10"><a href="#annotated-cell-3-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Raw promotion rate by group"</span>,</span>
<span id="annotated-cell-3-11"><a href="#annotated-cell-3-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Red dashed = the overall rate. Counts shown because the denominators do the arguing."</span>,</span>
<span id="annotated-cell-3-12"><a href="#annotated-cell-3-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Promotion rate"</span>, <span class="at">y =</span> <span class="cn">NULL</span></span>
<span id="annotated-cell-3-13"><a href="#annotated-cell-3-13" aria-hidden="true" tabindex="-1"></a>  )</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-3" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-3" data-code-lines="6" data-code-annotation="1">The counts on the bars deliberately. Two rates of 8% and 12% mean something completely different at n = 40 than at n = 400, and a bar chart of rates alone hides which situation you’re in — the single most common way a rate comparison misleads a stakeholder.</span>
</dd>
</dl>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="20-bayesian-ab-testing_files/figure-html/raw-rates-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>This example is not a randomised experiment, and the distinction matters
</div>
</div>
<div class="callout-body-container callout-body">
<p>Everything below is a valid Bayesian comparison of two rates. It is not an A/B <em>test</em>, because nobody assigned anyone to a group: membership of a diversity group is a characteristic people arrived with, not a treatment that was applied. Every confounder Chapter 21 is about — differences in role, tenure, function, manager — is still fully in play, and the Beta-Binomial machinery does nothing whatever about them.</p>
<p>The reason to use it as the worked example anyway is that the <em>arithmetic</em> of comparing two rates is identical either way, and this is the version a People Analytics team is asked for far more often than a true experiment. The reason to say so out loud is that the method’s output — “an 87% chance one rate is higher” — sounds equally authoritative in both cases, and only one of them licenses a causal reading.</p>
<p>When you do have random assignment (a training pilot with a randomised control group, a randomised change to an interview process), the same code below gives you a genuine causal answer. When you don’t, it gives you an accurate description of a difference whose cause is still open.</p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Handle this kind of comparison with care
</div>
</div>
<div class="callout-body-container callout-body">
<p>A raw or modelled promotion-rate gap between groups is a <strong>starting signal</strong>, not a conclusion. Real equity analysis needs to account for role, tenure, performance, and other legitimate factors before drawing any conclusion about a specific group difference, and — exactly as in Chapter 16 — usually belongs alongside legal and compensation expertise, sometimes under legal privilege, before it goes anywhere near a decision. Everything below is the <em>statistical method</em>, not a complete equity analysis on its own.</p>
</div>
</div>
<hr>
</section>
<section id="the-bayesian-ab-test" class="level2" data-number="20.3">
<h2 data-number="20.3" class="anchored" data-anchor-id="the-bayesian-ab-test"><span class="header-section-number">20.3</span> The Bayesian A/B test</h2>
<section id="one-posterior-per-group" class="level3" data-number="20.3.1">
<h3 data-number="20.3.1" class="anchored" data-anchor-id="one-posterior-per-group"><span class="header-section-number">20.3.1</span> One posterior per group</h3>
<p>Exactly as in Chapter 4, each group’s promotion rate gets a Beta posterior: start from a weakly-informative <code>Beta(2, 2)</code> prior (centred on 50%, easy to move), and update with each group’s promotions and non-promotions. Same habit as always — look at the prior before combining it with any data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">theta =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">400</span>)) <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">density =</span> <span class="fu">dbeta</span>(theta, <span class="dv">2</span>, <span class="dv">2</span>)) <span class="sc">|&gt;</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(theta, density)) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="at">fill =</span> navy, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">weighted.mean</span>(group_rates<span class="sc">$</span>raw_rate, group_rates<span class="sc">$</span>n),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> red) <span class="sc">+</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Prior for each group's promotion rate: Beta(2, 2)"</span>,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"A gentle hump centred on 50%. Red dashed = the rate the data will actually report."</span>,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Promotion rate"</span>, <span class="at">y =</span> <span class="st">"Prior density"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="20-bayesian-ab-testing_files/figure-html/plot-prior-ab-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>A prior centred a long way from the answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>That red line is a long way from the middle of the prior, and it’s worth being explicit about why that’s fine here and when it wouldn’t be.</p>
<p><code>Beta(2, 2)</code> is worth about <strong>two prior observations per group</strong> — a single notional promoted and a single notional not-promoted, plus the uniform baseline. Against denominators in the hundreds, it is overwhelmed immediately and the posterior sits essentially where the data puts it. If you knew the organisation’s overall promotion rate runs around 10%, a prior like <code>Beta(2, 18)</code> would encode that honestly and cost nothing — and with 30 people per group instead of 500, it would change the answer materially. Chapter 14 is the version of this argument where the prior is estimated from your own data rather than picked.</p>
<p>The habit worth keeping: look at where your prior sits relative to the answer <em>before</em> you combine them, so that if the two disagree you find out now rather than in the meeting.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>prior_a <span class="ot">&lt;-</span> <span class="dv">2</span>; prior_b <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>posteriors <span class="ot">&lt;-</span> group_rates <span class="sc">|&gt;</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">post_alpha =</span> prior_a <span class="sc">+</span> promoted_n,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">post_beta  =</span> prior_b <span class="sc">+</span> (n <span class="sc">-</span> promoted_n)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>posteriors</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  diverse_grp          n promoted_n raw_rate label          post_alpha post_beta
  &lt;chr&gt;            &lt;int&gt;      &lt;int&gt;    &lt;dbl&gt; &lt;chr&gt;               &lt;dbl&gt;     &lt;dbl&gt;
1 comparison_group   701        152   0.217  Comparison gr…        154       551
2 diverse_group      433         31   0.0716 Diversity gro…         33       404</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="annotated-cell-6"><pre class="sourceCode r code-annotation-code code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-6-1"><a href="#annotated-cell-6-1" aria-hidden="true" tabindex="-1"></a>theta_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fl">0.6</span>, <span class="at">length.out =</span> <span class="dv">400</span>)</span>
<span id="annotated-cell-6-2"><a href="#annotated-cell-6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-6-3"><a href="#annotated-cell-6-3" aria-hidden="true" tabindex="-1"></a>curves <span class="ot">&lt;-</span> posteriors <span class="sc">|&gt;</span></span>
<span id="annotated-cell-6-4"><a href="#annotated-cell-6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">reframe</span>(</span>
<span id="annotated-cell-6-5"><a href="#annotated-cell-6-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">theta =</span> theta_grid,</span>
<span id="annotated-cell-6-6"><a href="#annotated-cell-6-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">density =</span> <span class="fu">dbeta</span>(theta_grid, post_alpha, post_beta),</span>
<span id="annotated-cell-6-7"><a href="#annotated-cell-6-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">.by =</span> label</span>
<span id="annotated-cell-6-8"><a href="#annotated-cell-6-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="annotated-cell-6-9"><a href="#annotated-cell-6-9" aria-hidden="true" tabindex="-1"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-6" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-6-10" class="code-annotation-target"><a href="#annotated-cell-6-10" aria-hidden="true" tabindex="-1"></a>prior_curve <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="annotated-cell-6-11"><a href="#annotated-cell-6-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">theta =</span> theta_grid,</span>
<span id="annotated-cell-6-12"><a href="#annotated-cell-6-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">density =</span> <span class="fu">dbeta</span>(theta_grid, prior_a, prior_b)</span>
<span id="annotated-cell-6-13"><a href="#annotated-cell-6-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="annotated-cell-6-14"><a href="#annotated-cell-6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-6-15"><a href="#annotated-cell-6-15" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(curves, <span class="fu">aes</span>(<span class="at">x =</span> theta, <span class="at">y =</span> density)) <span class="sc">+</span></span>
<span id="annotated-cell-6-16"><a href="#annotated-cell-6-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="at">data =</span> prior_curve, <span class="at">fill =</span> <span class="st">"grey85"</span>, <span class="at">colour =</span> <span class="st">"grey60"</span>,</span>
<span id="annotated-cell-6-17"><a href="#annotated-cell-6-17" aria-hidden="true" tabindex="-1"></a>            <span class="at">linetype =</span> <span class="st">"dotted"</span>) <span class="sc">+</span></span>
<span id="annotated-cell-6-18"><a href="#annotated-cell-6-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="fu">aes</span>(<span class="at">fill =</span> label), <span class="at">alpha =</span> <span class="fl">0.25</span>, <span class="at">position =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="annotated-cell-6-19"><a href="#annotated-cell-6-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">colour =</span> label), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="annotated-cell-6-20"><a href="#annotated-cell-6-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Comparison group"</span> <span class="ot">=</span> navy_light,</span>
<span id="annotated-cell-6-21"><a href="#annotated-cell-6-21" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">"Diversity group"</span> <span class="ot">=</span> navy)) <span class="sc">+</span></span>
<span id="annotated-cell-6-22"><a href="#annotated-cell-6-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Comparison group"</span> <span class="ot">=</span> navy_light,</span>
<span id="annotated-cell-6-23"><a href="#annotated-cell-6-23" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"Diversity group"</span> <span class="ot">=</span> navy)) <span class="sc">+</span></span>
<span id="annotated-cell-6-24"><a href="#annotated-cell-6-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="annotated-cell-6-25"><a href="#annotated-cell-6-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="annotated-cell-6-26"><a href="#annotated-cell-6-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Prior and both posteriors, on one chart"</span>,</span>
<span id="annotated-cell-6-27"><a href="#annotated-cell-6-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Grey dotted = the Beta(2, 2) prior. Coloured curves = each group after seeing its data."</span>,</span>
<span id="annotated-cell-6-28"><a href="#annotated-cell-6-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Promotion rate"</span>, <span class="at">y =</span> <span class="st">"Density"</span>, <span class="at">colour =</span> <span class="cn">NULL</span>, <span class="at">fill =</span> <span class="cn">NULL</span></span>
<span id="annotated-cell-6-29"><a href="#annotated-cell-6-29" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="annotated-cell-6-30"><a href="#annotated-cell-6-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"top"</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-6" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-6" data-code-lines="10" data-code-annotation="1">The prior drawn on the same axes as the posteriors, deliberately — Chapter 5’s habit, and the clearest single picture of what Bayesian updating actually did here. The flat grey hump is what we believed beforehand; the two narrow spikes are what 1,100 records did to it.</span>
</dd>
</dl>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="20-bayesian-ab-testing_files/figure-html/posterior-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The gap between the grey and the coloured curves is the whole point of the exercise: almost all of the information in those posteriors came from the data, which is exactly what you want a weakly-informative prior to produce. The gap between the two <em>coloured</em> curves is the finding, and how much they overlap is the honest answer to “is this real.”</p>
</section>
<section id="the-question-a-p-value-doesnt-answer-directly-pa-beats-b" class="level3" data-number="20.3.2">
<h3 data-number="20.3.2" class="anchored" data-anchor-id="the-question-a-p-value-doesnt-answer-directly-pa-beats-b"><span class="header-section-number">20.3.2</span> The question a p-value doesn’t answer directly: P(A beats B)</h3>
<p>This is Chapter 5’s technique — subtract the draws — applied to two Beta posteriors instead of two Normal ones. Draw many samples from each posterior, subtract them element by element, and count how often the difference lands above zero. Simple, and exactly what most stakeholders actually want to know:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>n_draws <span class="ot">&lt;-</span> <span class="dv">100000</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>samples <span class="ot">&lt;-</span> posteriors <span class="sc">|&gt;</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">reframe</span>(</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">draw =</span> <span class="dv">1</span><span class="sc">:</span>n_draws,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sample =</span> <span class="fu">rbeta</span>(n_draws, post_alpha, post_beta),</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">.by =</span> diverse_grp</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> diverse_grp, <span class="at">values_from =</span> sample, <span class="at">id_cols =</span> draw)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>samples <span class="ot">&lt;-</span> samples <span class="sc">|&gt;</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">diff =</span> diverse_group <span class="sc">-</span> comparison_group)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>p_higher <span class="ot">&lt;-</span> <span class="fu">mean</span>(samples<span class="sc">$</span>diff <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>p_higher</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(samples, <span class="fu">aes</span>(<span class="at">x =</span> diff)) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">60</span>, <span class="at">fill =</span> navy_light, <span class="at">colour =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> red) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Posterior distribution of the difference in promotion rates"</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">paste0</span>(<span class="st">"Red dashed = no difference. P(difference &gt; 0) = "</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>                      scales<span class="sc">::</span><span class="fu">percent</span>(p_higher, <span class="at">accuracy =</span> <span class="fl">0.1</span>)),</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Difference in promotion rate (diversity group − comparison group)"</span>,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Posterior draws"</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="20-bayesian-ab-testing_files/figure-html/diff-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>diff_ci <span class="ot">&lt;-</span> <span class="fu">quantile</span>(samples<span class="sc">$</span>diff, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span>))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>diff_ci</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      2.5%        50%      97.5% 
-0.1821827 -0.1430129 -0.1033531 </code></pre>
</div>
</div>
<p>Those three numbers are the finding, so here they are in the form you’d actually say them — the difference in <strong>percentage points</strong>, which is the unit a stakeholder thinks in:</p>
<blockquote class="blockquote">
<p><strong>The diversity group’s promotion rate is -14.3% different from the comparison group’s, with a 95% credible interval running from -18.2% to -10.3%. The probability the diversity group’s underlying rate is genuinely higher is 0.0%.</strong></p>
</blockquote>
<p>Read the interval before the probability. If it straddles zero, the probability statement is telling you which side of the fence the bulk of the posterior sits on — not that a difference has been established.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Two workflow steps that legitimately don’t apply here
</div>
</div>
<div class="callout-body-container callout-body">
<p>Chapter 10’s nine steps include diagnosing the sampler (step 6) and a posterior predictive check (step 7), and this chapter does neither. That’s correct, and worth being explicit about so it doesn’t read as a shortcut.</p>
<p><strong>There is no sampler to diagnose.</strong> A Beta prior updated by binomial data gives a Beta posterior <em>exactly</em> — that’s what “conjugate” means. <code>rbeta()</code> above is drawing from a distribution we already know in closed form, not exploring an unknown posterior by MCMC. There is no <code>Rhat</code>, because there are no chains that could fail to agree.</p>
<p><strong>The posterior predictive check is nearly trivial.</strong> With two groups, two counts and two denominators, the model has as many parameters as it has data points to reproduce. It will match the observed promotion counts essentially by construction, so a check that it does tells you nothing.</p>
<p>The general lesson, which arrives properly in Chapter 21: the workflow is a checklist, not a ritual. Skipping a step because it cannot inform you is different from skipping it because you didn’t get round to it — and the difference is that you can say which one you did.</p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Reporting this properly
</div>
</div>
<div class="callout-body-container callout-body">
<p>Report <strong>three things together</strong>, not a single number: the probability the groups genuinely differ (0.0% here), the likely <em>size</em> of the difference (the credible interval), and whether that size is big enough to matter for a real decision. A 99%-confident but tiny difference and an 80%-confident but large one often call for different actions — collapsing both into “significant / not significant” throws that distinction away.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="is-the-difference-big-enough-to-act-on" class="level2" data-number="20.4">
<h2 data-number="20.4" class="anchored" data-anchor-id="is-the-difference-big-enough-to-act-on"><span class="header-section-number">20.4</span> Is the difference big enough to act on?</h2>
<p>A <strong>region of practical equivalence (ROPE)</strong> makes this explicit: pick the smallest difference in promotion rate you’d actually consider meaningful (say, 3 percentage points), and ask how much of the posterior falls outside it.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>rope_width <span class="ot">&lt;-</span> <span class="fl">0.03</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>rope_result <span class="ot">&lt;-</span> samples <span class="sc">|&gt;</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_practically_higher =</span> <span class="fu">mean</span>(diff <span class="sc">&gt;</span> rope_width),</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_practically_lower  =</span> <span class="fu">mean</span>(diff <span class="sc">&lt;</span> <span class="sc">-</span>rope_width),</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_practically_equivalent =</span> <span class="fu">mean</span>(<span class="fu">abs</span>(diff) <span class="sc">&lt;=</span> rope_width)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>rope_result</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  p_practically_higher p_practically_lower p_practically_equivalent
                 &lt;dbl&gt;               &lt;dbl&gt;                    &lt;dbl&gt;
1                    0                   1                        0</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="annotated-cell-11"><pre class="sourceCode r code-annotation-code code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-11-1"><a href="#annotated-cell-11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(samples, <span class="fu">aes</span>(<span class="at">x =</span> diff)) <span class="sc">+</span></span>
<span id="annotated-cell-11-2"><a href="#annotated-cell-11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">60</span>, <span class="at">fill =</span> navy_light, <span class="at">colour =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="annotated-cell-11-3"><a href="#annotated-cell-11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"rect"</span>, <span class="at">xmin =</span> <span class="sc">-</span>rope_width, <span class="at">xmax =</span> rope_width,</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-11" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-11-4" class="code-annotation-target"><a href="#annotated-cell-11-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">ymin =</span> <span class="sc">-</span><span class="cn">Inf</span>, <span class="at">ymax =</span> <span class="cn">Inf</span>, <span class="at">fill =</span> <span class="st">"grey50"</span>, <span class="at">alpha =</span> <span class="fl">0.18</span>) <span class="sc">+</span></span>
<span id="annotated-cell-11-5"><a href="#annotated-cell-11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">c</span>(<span class="sc">-</span>rope_width, rope_width),</span>
<span id="annotated-cell-11-6"><a href="#annotated-cell-11-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> red) <span class="sc">+</span></span>
<span id="annotated-cell-11-7"><a href="#annotated-cell-11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="annotated-cell-11-8"><a href="#annotated-cell-11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="annotated-cell-11-9"><a href="#annotated-cell-11-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"The same posterior, with a region of practical equivalence"</span>,</span>
<span id="annotated-cell-11-10"><a href="#annotated-cell-11-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">paste0</span>(</span>
<span id="annotated-cell-11-11"><a href="#annotated-cell-11-11" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Shaded band = differences too small to act on (±3pp). "</span>,</span>
<span id="annotated-cell-11-12"><a href="#annotated-cell-11-12" aria-hidden="true" tabindex="-1"></a>      scales<span class="sc">::</span><span class="fu">percent</span>(rope_result<span class="sc">$</span>p_practically_equivalent, <span class="at">accuracy =</span> <span class="fl">0.1</span>),</span>
<span id="annotated-cell-11-13"><a href="#annotated-cell-11-13" aria-hidden="true" tabindex="-1"></a>      <span class="st">" of the posterior falls inside it."</span>),</span>
<span id="annotated-cell-11-14"><a href="#annotated-cell-11-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Difference in promotion rate"</span>, <span class="at">y =</span> <span class="st">"Posterior draws"</span></span>
<span id="annotated-cell-11-15"><a href="#annotated-cell-11-15" aria-hidden="true" tabindex="-1"></a>  )</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-11" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-11" data-code-lines="4" data-code-annotation="1">The ROPE drawn as a band rather than described in a table. This is the chart to show a stakeholder, because it converts “is there a difference” into “is the difference in the zone we said we’d care about” — a question they set the terms of, not you.</span>
</dd>
</dl>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="20-bayesian-ab-testing_files/figure-html/rope-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Read the three numbers as a set that has to add to one. The two outer columns are the probability the difference is <strong>big enough to matter</strong> in each direction; the middle column is the probability it is real but too small to act on, or absent altogether.</p>
<blockquote class="blockquote">
<p><strong>0% of the posterior falls inside ±3 percentage points — the range we agreed in advance was too small to change anything. The probability the gap is larger than that in either direction is 100%.</strong></p>
</blockquote>
<p>This reframes “is there a difference” as “is there a difference big enough to be worth acting on” — usually the actual question behind the request. The critical procedural point: <strong>pick the ROPE width before you see the posterior.</strong> Choosing it afterwards, once you know where the distribution sits, is p-hacking with different vocabulary.</p>
<hr>
</section>
<section id="how-this-compares-to-other-approaches" class="level2" data-number="20.5">
<h2 data-number="20.5" class="anchored" data-anchor-id="how-this-compares-to-other-approaches"><span class="header-section-number">20.5</span> How this compares to other approaches</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>A different lens: the classical two-proportion test
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>prop.test()</code> or a chi-square test asks: <em>if the two groups truly had the same promotion rate, how unusual would data this different be?</em> — producing a p-value. The Bayesian version above asks the question most stakeholders actually mean when they say “is this real”: <em>given the data we’ve seen, how likely is it that the rates genuinely differ, and by how much?</em> With the sample sizes typical of People Analytics work, the two methods usually agree on direction; the Bayesian version’s edge is answering the second, size-and-confidence question directly, in one step, without a separate power calculation.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> group_rates<span class="sc">$</span>promoted_n, <span class="at">n =</span> group_rates<span class="sc">$</span>n)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions with continuity correction

data:  group_rates$promoted_n out of group_rates$n
X-squared = 40.655, df = 1, p-value = 1.816e-10
alternative hypothesis: two.sided
95 percent confidence interval:
 0.1043809 0.1860983
sample estimates:
    prop 1     prop 2 
0.21683310 0.07159353 </code></pre>
</div>
</div>
<p>Worth reading against the Bayesian output above, line by line, because the two are closer than the philosophical argument suggests:</p>
<ul>
<li><strong><code>p-value</code></strong> — the probability of seeing a gap at least this large <em>if the two rates were truly identical</em>. Note the direction of that sentence. It is not the probability that the rates are the same, and it is not the probability the gap is real, which is what 0.0% above actually gives you.</li>
<li><strong><code>95 percent confidence interval</code></strong> — compare it directly to the credible interval from <code>quantile(samples$diff, ...)</code>. With hundreds of observations per group and a weak prior, the two will land in nearly the same place, which is the honest version of “these methods usually agree.” What differs is what you’re allowed to say about the interval: the credible interval is a statement about where the difference probably is, the confidence interval is a statement about the procedure that produced it.</li>
<li><strong><code>sample estimates</code></strong> — the two raw rates, unchanged from <code>group_rates</code>. No shrinkage, no prior, no pooling.</li>
</ul>
<p>The one thing <code>prop.test()</code> does not give you at all is the ROPE question. There is no way to ask it “how likely is the gap bigger than three percentage points,” because it only ever tests against exactly zero.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why this book uses estimation, not Bayes Factors, for this kind of test
</div>
</div>
<div class="callout-body-container callout-body">
<p>Keith McNulty’s book covers <strong>Bayesian hypothesis testing</strong> using <strong>Bayes Factors</strong> — comparing the evidence for “the rates are equal” against “the rates differ” as a ratio, the Bayesian analogue of a p-value-producing test. It’s a legitimate and well-developed approach, useful in particular when the actual question is <em>“is there truly a non-zero effect at all?”</em> — common in scientific replication contexts, and covered in his Chapter 12. This book leans instead on the estimation approach above (posteriors, credible intervals, and a ROPE), because the questions People Analytics usually needs answered are “how big” and “are we confident enough to act,” not “is the effect exactly zero” — and estimation answers those directly, in the same units as the decision. Bayes Factors can also be sensitive to exactly how you specify the alternative hypothesis, which adds a layer of judgment estimation avoids. Neither is “the correct Bayesian method” — pick the one that matches the actual question.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>For the ML/DS crowd
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you’ve heard of <strong>Thompson sampling</strong> or <strong>multi-armed bandits</strong> — used in live experimentation platforms and recommender systems to decide which variant to show next — you’ve seen this exact method running continuously. Thompson sampling literally draws one sample from each arm’s Beta posterior and picks whichever arm’s sample is highest, repeating as data arrives; it’s the sequential, automated sibling of the one-shot comparison in this chapter. The maths is identical — sampling from Beta posteriors and comparing — just wired into a live decision loop instead of a one-time analysis.</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Caution</span>Try it yourself
</div>
</div>
<div class="callout-body-container callout-body">
<p>Rerun this comparison for <code>flexible</code> vs.&nbsp;not, and separately for <code>store</code> vs.&nbsp;not. Do either of those produce a clearer signal than <code>diverse</code> did? Report your answer the way you would to a stakeholder — probability of a real difference, likely size, and whether it clears your ROPE.</p>
</div>
</div>
<hr>
</section>
<section id="on-the-job" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="on-the-job">On the job</h2>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Why this matters day to day
</div>
</div>
<div class="callout-body-container callout-body">
<p>Most People Analytics “did X work” questions are exactly this shape — two groups, a rate, and a decision to make with a modest sample. This method scales down gracefully to small groups (unlike a chi-square test, which gets unreliable with few observations per cell), gives you a direct, presentable probability statement, and — via the ROPE — keeps you honest about the difference between “statistically distinguishable” and “big enough to matter.”</p>
</div>
</div>
<hr>
</section>
<section id="summary" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="summary">Summary</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Today you learned
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>A Bayesian A/B test puts a Beta posterior on each group’s rate and compares them <strong>directly by sampling</strong>, rather than via a significance test.</li>
<li><strong>P(A beats B)</strong> and the <strong>credible interval on the difference</strong> together answer “is it real” and “how big,” in one step.</li>
<li>A <strong>ROPE</strong> turns “is there a difference” into the more useful “is the difference big enough to act on.”</li>
<li>This book favours estimation over Bayes-Factor hypothesis testing for exactly this kind of question — see the note above for when you’d reach for the other approach instead.</li>
<li>Comparisons involving protected characteristics need the same care as the pay analysis in Chapter 16 — a statistical signal, not a complete equity conclusion on its own.</li>
<li>The <strong>arithmetic is the same whether or not anyone was randomised, and the licence to interpret it isn’t.</strong> With random assignment this is a causal answer; without it — as in this chapter’s worked example — it is an accurate description of a difference whose cause is still open, and Chapters 21 and 22 are what you reach for next.</li>
<li>Set the <strong>ROPE width before you look at the posterior</strong>. Choosing it afterwards is p-hacking in different clothes.</li>
</ol>
</div>
</div>
</section>
<section id="next-chapter" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="next-chapter">Next chapter</h2>
<p><strong>Causal structure: drawing the graph</strong> — an A/B test is the easy case, because you controlled who went into which group. The next two chapters are about the far more common situation where you didn’t, and what can still be said.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/19-measurement-error-missing-data.html" class="pagination-link" aria-label="Modelling What You Can't See: Measurement Error, Missing Data &amp; Latent Variables">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Modelling What You Can’t See: Measurement Error, Missing Data &amp; Latent Variables</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/21-causal-structure-dags.html" class="pagination-link" aria-label="Causal Structure: Drawing the Graph">
        <span class="nav-page-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Causal Structure: Drawing the Graph</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Bayesian A/B Testing for People Experiments</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">## Welcome back {.unnumbered}</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>People Analytics runs experiments constantly, even when nobody calls</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>them that: did the new interview process change the hire rate, did the</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>flexible-work pilot change retention, does one group's promotion rate</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>genuinely differ from another's. Unlike a web A/B test with millions of</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>visitors overnight, these experiments usually have **dozens or</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>hundreds** of people in each group, and the answer is needed for a</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>decision, not a p-value.</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>This chapter builds a Bayesian A/B test from the same Beta-Binomial</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>machinery you met in Chapter 4, and shows why its output — "there's an</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>87% chance A beats B, and if it does, it's probably by 2–9 points" — is</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>usually a better fit for a People Analytics decision than a</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>significance test.</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a><span class="fu">## What you'll be able to do by the end {.unnumbered}</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>Set up a Bayesian A/B test for two groups' rates using Beta</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>    posteriors</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>Compute **P(A beats B)** directly from posterior samples</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>Report the size of a likely difference, not just its direction</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span>Compare this to a classical proportions test and to Bayes-Factor</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>    hypothesis testing, and know when each is the better tool</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a><span class="ss">5.  </span>Apply appropriate care when the "test" involves a protected</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>    characteristic</span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a><span class="fu">## Setup</span></span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a><span class="in">```{r setup}</span></span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(peopleanalyticsdata)</span>
<span id="cb15-37"><a href="#cb15-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-38"><a href="#cb15-38" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>))</span>
<span id="cb15-39"><a href="#cb15-39" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb15-40"><a href="#cb15-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-41"><a href="#cb15-41" aria-hidden="true" tabindex="-1"></a><span class="co"># Shared colour tokens (matching theme/academicdesign*.scss). Navy and light</span></span>
<span id="cb15-42"><a href="#cb15-42" aria-hidden="true" tabindex="-1"></a><span class="co"># navy carry the data; red is reserved for reference lines and annotations,</span></span>
<span id="cb15-43"><a href="#cb15-43" aria-hidden="true" tabindex="-1"></a><span class="co"># never for a second data series.</span></span>
<span id="cb15-44"><a href="#cb15-44" aria-hidden="true" tabindex="-1"></a>navy       <span class="ot">&lt;-</span> <span class="st">"#122a52"</span></span>
<span id="cb15-45"><a href="#cb15-45" aria-hidden="true" tabindex="-1"></a>navy_light <span class="ot">&lt;-</span> <span class="st">"#8fabd0"</span></span>
<span id="cb15-46"><a href="#cb15-46" aria-hidden="true" tabindex="-1"></a>red        <span class="ot">&lt;-</span> <span class="st">"#d32f2f"</span></span>
<span id="cb15-47"><a href="#cb15-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-48"><a href="#cb15-48" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"promotion"</span>, <span class="at">package =</span> <span class="st">"peopleanalyticsdata"</span>)</span>
<span id="cb15-49"><a href="#cb15-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-50"><a href="#cb15-50" aria-hidden="true" tabindex="-1"></a><span class="co"># Guard against missing values before grouping and modelling (Chapter 1</span></span>
<span id="cb15-51"><a href="#cb15-51" aria-hidden="true" tabindex="-1"></a><span class="co"># found gaps in a similar teaching dataset).</span></span>
<span id="cb15-52"><a href="#cb15-52" aria-hidden="true" tabindex="-1"></a>promotion <span class="ot">&lt;-</span> promotion <span class="sc">|&gt;</span> <span class="fu">drop_na</span>(diverse, flexible, store, promoted)</span>
<span id="cb15-53"><a href="#cb15-53" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-54"><a href="#cb15-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-55"><a href="#cb15-55" aria-hidden="true" tabindex="-1"></a><span class="in">`promotion`</span> has 1,134 employee records from a retail company: <span class="in">`diverse`</span></span>
<span id="cb15-56"><a href="#cb15-56" aria-hidden="true" tabindex="-1"></a>(membership of a diversity group at the company), <span class="in">`flexible`</span> (worked</span>
<span id="cb15-57"><a href="#cb15-57" aria-hidden="true" tabindex="-1"></a>part-time for 6+ months), <span class="in">`store`</span> (joined working in retail stores),</span>
<span id="cb15-58"><a href="#cb15-58" aria-hidden="true" tabindex="-1"></a>and <span class="in">`promoted`</span> (the outcome).</span>
<span id="cb15-59"><a href="#cb15-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-60"><a href="#cb15-60" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb15-61"><a href="#cb15-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-62"><a href="#cb15-62" aria-hidden="true" tabindex="-1"></a><span class="fu">## The question</span></span>
<span id="cb15-63"><a href="#cb15-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-64"><a href="#cb15-64" aria-hidden="true" tabindex="-1"></a>Promotion-rate comparisons between groups are one of the most common —</span>
<span id="cb15-65"><a href="#cb15-65" aria-hidden="true" tabindex="-1"></a>and most consequential — comparisons a People Analytics team is asked</span>
<span id="cb15-66"><a href="#cb15-66" aria-hidden="true" tabindex="-1"></a>to make, often as part of routine equity monitoring. We'll use it as</span>
<span id="cb15-67"><a href="#cb15-67" aria-hidden="true" tabindex="-1"></a>our worked example:</span>
<span id="cb15-68"><a href="#cb15-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-69"><a href="#cb15-69" aria-hidden="true" tabindex="-1"></a><span class="in">```{r raw-rates}</span></span>
<span id="cb15-70"><a href="#cb15-70" aria-hidden="true" tabindex="-1"></a><span class="co"># `diverse` may be coded as Y/N or 1/0 depending on data version — normalise</span></span>
<span id="cb15-71"><a href="#cb15-71" aria-hidden="true" tabindex="-1"></a><span class="co"># to an explicit, readable label so every downstream step is unambiguous.</span></span>
<span id="cb15-72"><a href="#cb15-72" aria-hidden="true" tabindex="-1"></a>promotion <span class="ot">&lt;-</span> promotion <span class="sc">|&gt;</span></span>
<span id="cb15-73"><a href="#cb15-73" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">diverse_grp =</span> <span class="fu">if_else</span>(diverse <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Y"</span>, <span class="st">"1"</span>, <span class="dv">1</span>, <span class="cn">TRUE</span>),</span>
<span id="cb15-74"><a href="#cb15-74" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"diverse_group"</span>, <span class="st">"comparison_group"</span>))</span>
<span id="cb15-75"><a href="#cb15-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-76"><a href="#cb15-76" aria-hidden="true" tabindex="-1"></a>group_rates <span class="ot">&lt;-</span> promotion <span class="sc">|&gt;</span></span>
<span id="cb15-77"><a href="#cb15-77" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(diverse_grp) <span class="sc">|&gt;</span></span>
<span id="cb15-78"><a href="#cb15-78" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb15-79"><a href="#cb15-79" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb15-80"><a href="#cb15-80" aria-hidden="true" tabindex="-1"></a>    <span class="at">promoted_n =</span> <span class="fu">sum</span>(promoted <span class="sc">==</span> <span class="dv">1</span> <span class="sc">|</span> promoted <span class="sc">==</span> <span class="st">"Y"</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb15-81"><a href="#cb15-81" aria-hidden="true" tabindex="-1"></a>    <span class="at">raw_rate =</span> promoted_n <span class="sc">/</span> n</span>
<span id="cb15-82"><a href="#cb15-82" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb15-83"><a href="#cb15-83" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">label =</span> <span class="fu">if_else</span>(diverse_grp <span class="sc">==</span> <span class="st">"diverse_group"</span>,</span>
<span id="cb15-84"><a href="#cb15-84" aria-hidden="true" tabindex="-1"></a>                         <span class="st">"Diversity group"</span>, <span class="st">"Comparison group"</span>))       <span class="co"># &lt;1&gt;</span></span>
<span id="cb15-85"><a href="#cb15-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-86"><a href="#cb15-86" aria-hidden="true" tabindex="-1"></a>group_rates</span>
<span id="cb15-87"><a href="#cb15-87" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-88"><a href="#cb15-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-89"><a href="#cb15-89" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>A presentation-ready label alongside the raw coding. Legends and axis</span>
<span id="cb15-90"><a href="#cb15-90" aria-hidden="true" tabindex="-1"></a>    labels in this book never show a raw variable value — <span class="in">`diverse_grp`</span></span>
<span id="cb15-91"><a href="#cb15-91" aria-hidden="true" tabindex="-1"></a>    is for the code, <span class="in">`label`</span> is for the reader.</span>
<span id="cb15-92"><a href="#cb15-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-93"><a href="#cb15-93" aria-hidden="true" tabindex="-1"></a>Describe it, then plot it — Chapter 10's step 2, and worth doing even when</span>
<span id="cb15-94"><a href="#cb15-94" aria-hidden="true" tabindex="-1"></a>the data is only four numbers, because the plot is where the sample sizes</span>
<span id="cb15-95"><a href="#cb15-95" aria-hidden="true" tabindex="-1"></a>become visible:</span>
<span id="cb15-96"><a href="#cb15-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-97"><a href="#cb15-97" aria-hidden="true" tabindex="-1"></a><span class="in">```{r raw-rates-plot}</span></span>
<span id="cb15-98"><a href="#cb15-98" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(group_rates, <span class="fu">aes</span>(<span class="at">x =</span> raw_rate, <span class="at">y =</span> <span class="fu">fct_rev</span>(label))) <span class="sc">+</span></span>
<span id="cb15-99"><a href="#cb15-99" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> navy_light, <span class="at">colour =</span> navy, <span class="at">width =</span> <span class="fl">0.55</span>) <span class="sc">+</span></span>
<span id="cb15-100"><a href="#cb15-100" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">weighted.mean</span>(group_rates<span class="sc">$</span>raw_rate, group_rates<span class="sc">$</span>n),</span>
<span id="cb15-101"><a href="#cb15-101" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> red) <span class="sc">+</span></span>
<span id="cb15-102"><a href="#cb15-102" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(promoted_n, <span class="st">" of "</span>, n)),</span>
<span id="cb15-103"><a href="#cb15-103" aria-hidden="true" tabindex="-1"></a>            <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.15</span>, <span class="at">size =</span> <span class="fl">3.4</span>, <span class="at">colour =</span> navy) <span class="sc">+</span>                <span class="co"># &lt;1&gt;</span></span>
<span id="cb15-104"><a href="#cb15-104" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent,</span>
<span id="cb15-105"><a href="#cb15-105" aria-hidden="true" tabindex="-1"></a>                     <span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.25</span>))) <span class="sc">+</span></span>
<span id="cb15-106"><a href="#cb15-106" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-107"><a href="#cb15-107" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Raw promotion rate by group"</span>,</span>
<span id="cb15-108"><a href="#cb15-108" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Red dashed = the overall rate. Counts shown because the denominators do the arguing."</span>,</span>
<span id="cb15-109"><a href="#cb15-109" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Promotion rate"</span>, <span class="at">y =</span> <span class="cn">NULL</span></span>
<span id="cb15-110"><a href="#cb15-110" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb15-111"><a href="#cb15-111" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-112"><a href="#cb15-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-113"><a href="#cb15-113" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>The counts on the bars deliberately. Two rates of 8% and 12% mean</span>
<span id="cb15-114"><a href="#cb15-114" aria-hidden="true" tabindex="-1"></a>    something completely different at n = 40 than at n = 400, and a bar</span>
<span id="cb15-115"><a href="#cb15-115" aria-hidden="true" tabindex="-1"></a>    chart of rates alone hides which situation you're in — the single most</span>
<span id="cb15-116"><a href="#cb15-116" aria-hidden="true" tabindex="-1"></a>    common way a rate comparison misleads a stakeholder.</span>
<span id="cb15-117"><a href="#cb15-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-118"><a href="#cb15-118" aria-hidden="true" tabindex="-1"></a>::: callout-important</span>
<span id="cb15-119"><a href="#cb15-119" aria-hidden="true" tabindex="-1"></a><span class="fu">## This example is not a randomised experiment, and the distinction matters</span></span>
<span id="cb15-120"><a href="#cb15-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-121"><a href="#cb15-121" aria-hidden="true" tabindex="-1"></a>Everything below is a valid Bayesian comparison of two rates. It is not</span>
<span id="cb15-122"><a href="#cb15-122" aria-hidden="true" tabindex="-1"></a>an A/B *test*, because nobody assigned anyone to a group: membership of a</span>
<span id="cb15-123"><a href="#cb15-123" aria-hidden="true" tabindex="-1"></a>diversity group is a characteristic people arrived with, not a treatment</span>
<span id="cb15-124"><a href="#cb15-124" aria-hidden="true" tabindex="-1"></a>that was applied. Every confounder Chapter 21 is about — differences in</span>
<span id="cb15-125"><a href="#cb15-125" aria-hidden="true" tabindex="-1"></a>role, tenure, function, manager — is still fully in play, and the</span>
<span id="cb15-126"><a href="#cb15-126" aria-hidden="true" tabindex="-1"></a>Beta-Binomial machinery does nothing whatever about them.</span>
<span id="cb15-127"><a href="#cb15-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-128"><a href="#cb15-128" aria-hidden="true" tabindex="-1"></a>The reason to use it as the worked example anyway is that the *arithmetic*</span>
<span id="cb15-129"><a href="#cb15-129" aria-hidden="true" tabindex="-1"></a>of comparing two rates is identical either way, and this is the version a</span>
<span id="cb15-130"><a href="#cb15-130" aria-hidden="true" tabindex="-1"></a>People Analytics team is asked for far more often than a true experiment.</span>
<span id="cb15-131"><a href="#cb15-131" aria-hidden="true" tabindex="-1"></a>The reason to say so out loud is that the method's output — "an 87% chance</span>
<span id="cb15-132"><a href="#cb15-132" aria-hidden="true" tabindex="-1"></a>one rate is higher" — sounds equally authoritative in both cases, and only</span>
<span id="cb15-133"><a href="#cb15-133" aria-hidden="true" tabindex="-1"></a>one of them licenses a causal reading.</span>
<span id="cb15-134"><a href="#cb15-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-135"><a href="#cb15-135" aria-hidden="true" tabindex="-1"></a>When you do have random assignment (a training pilot with a randomised</span>
<span id="cb15-136"><a href="#cb15-136" aria-hidden="true" tabindex="-1"></a>control group, a randomised change to an interview process), the same code</span>
<span id="cb15-137"><a href="#cb15-137" aria-hidden="true" tabindex="-1"></a>below gives you a genuine causal answer. When you don't, it gives you an</span>
<span id="cb15-138"><a href="#cb15-138" aria-hidden="true" tabindex="-1"></a>accurate description of a difference whose cause is still open.</span>
<span id="cb15-139"><a href="#cb15-139" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb15-140"><a href="#cb15-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-141"><a href="#cb15-141" aria-hidden="true" tabindex="-1"></a>::: callout-important</span>
<span id="cb15-142"><a href="#cb15-142" aria-hidden="true" tabindex="-1"></a><span class="fu">## Handle this kind of comparison with care</span></span>
<span id="cb15-143"><a href="#cb15-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-144"><a href="#cb15-144" aria-hidden="true" tabindex="-1"></a>A raw or modelled promotion-rate gap between groups is a **starting</span>
<span id="cb15-145"><a href="#cb15-145" aria-hidden="true" tabindex="-1"></a>signal**, not a conclusion. Real equity analysis needs to account for</span>
<span id="cb15-146"><a href="#cb15-146" aria-hidden="true" tabindex="-1"></a>role, tenure, performance, and other legitimate factors before drawing</span>
<span id="cb15-147"><a href="#cb15-147" aria-hidden="true" tabindex="-1"></a>any conclusion about a specific group difference, and — exactly as in</span>
<span id="cb15-148"><a href="#cb15-148" aria-hidden="true" tabindex="-1"></a>Chapter 16 — usually belongs alongside legal and compensation</span>
<span id="cb15-149"><a href="#cb15-149" aria-hidden="true" tabindex="-1"></a>expertise, sometimes under legal privilege, before it goes anywhere</span>
<span id="cb15-150"><a href="#cb15-150" aria-hidden="true" tabindex="-1"></a>near a decision. Everything below is the *statistical method*, not a</span>
<span id="cb15-151"><a href="#cb15-151" aria-hidden="true" tabindex="-1"></a>complete equity analysis on its own.</span>
<span id="cb15-152"><a href="#cb15-152" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb15-153"><a href="#cb15-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-154"><a href="#cb15-154" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb15-155"><a href="#cb15-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-156"><a href="#cb15-156" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Bayesian A/B test</span></span>
<span id="cb15-157"><a href="#cb15-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-158"><a href="#cb15-158" aria-hidden="true" tabindex="-1"></a><span class="fu">### One posterior per group</span></span>
<span id="cb15-159"><a href="#cb15-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-160"><a href="#cb15-160" aria-hidden="true" tabindex="-1"></a>Exactly as in Chapter 4, each group's promotion rate gets a Beta</span>
<span id="cb15-161"><a href="#cb15-161" aria-hidden="true" tabindex="-1"></a>posterior: start from a weakly-informative <span class="in">`Beta(2, 2)`</span> prior (centred</span>
<span id="cb15-162"><a href="#cb15-162" aria-hidden="true" tabindex="-1"></a>on 50%, easy to move), and update with each group's promotions and</span>
<span id="cb15-163"><a href="#cb15-163" aria-hidden="true" tabindex="-1"></a>non-promotions. Same habit as always — look at the prior before</span>
<span id="cb15-164"><a href="#cb15-164" aria-hidden="true" tabindex="-1"></a>combining it with any data:</span>
<span id="cb15-165"><a href="#cb15-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-166"><a href="#cb15-166" aria-hidden="true" tabindex="-1"></a><span class="in">```{r plot-prior-ab}</span></span>
<span id="cb15-167"><a href="#cb15-167" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">theta =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">400</span>)) <span class="sc">|&gt;</span></span>
<span id="cb15-168"><a href="#cb15-168" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">density =</span> <span class="fu">dbeta</span>(theta, <span class="dv">2</span>, <span class="dv">2</span>)) <span class="sc">|&gt;</span></span>
<span id="cb15-169"><a href="#cb15-169" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(theta, density)) <span class="sc">+</span></span>
<span id="cb15-170"><a href="#cb15-170" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="at">fill =</span> navy, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb15-171"><a href="#cb15-171" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">weighted.mean</span>(group_rates<span class="sc">$</span>raw_rate, group_rates<span class="sc">$</span>n),</span>
<span id="cb15-172"><a href="#cb15-172" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> red) <span class="sc">+</span></span>
<span id="cb15-173"><a href="#cb15-173" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb15-174"><a href="#cb15-174" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Prior for each group's promotion rate: Beta(2, 2)"</span>,</span>
<span id="cb15-175"><a href="#cb15-175" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"A gentle hump centred on 50%. Red dashed = the rate the data will actually report."</span>,</span>
<span id="cb15-176"><a href="#cb15-176" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Promotion rate"</span>, <span class="at">y =</span> <span class="st">"Prior density"</span>)</span>
<span id="cb15-177"><a href="#cb15-177" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-178"><a href="#cb15-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-179"><a href="#cb15-179" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb15-180"><a href="#cb15-180" aria-hidden="true" tabindex="-1"></a><span class="fu">## A prior centred a long way from the answer</span></span>
<span id="cb15-181"><a href="#cb15-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-182"><a href="#cb15-182" aria-hidden="true" tabindex="-1"></a>That red line is a long way from the middle of the prior, and it's worth</span>
<span id="cb15-183"><a href="#cb15-183" aria-hidden="true" tabindex="-1"></a>being explicit about why that's fine here and when it wouldn't be.</span>
<span id="cb15-184"><a href="#cb15-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-185"><a href="#cb15-185" aria-hidden="true" tabindex="-1"></a><span class="in">`Beta(2, 2)`</span> is worth about **two prior observations per group** — a</span>
<span id="cb15-186"><a href="#cb15-186" aria-hidden="true" tabindex="-1"></a>single notional promoted and a single notional not-promoted, plus the</span>
<span id="cb15-187"><a href="#cb15-187" aria-hidden="true" tabindex="-1"></a>uniform baseline. Against denominators in the hundreds, it is</span>
<span id="cb15-188"><a href="#cb15-188" aria-hidden="true" tabindex="-1"></a>overwhelmed immediately and the posterior sits essentially where the data</span>
<span id="cb15-189"><a href="#cb15-189" aria-hidden="true" tabindex="-1"></a>puts it. If you knew the organisation's overall promotion rate runs around</span>
<span id="cb15-190"><a href="#cb15-190" aria-hidden="true" tabindex="-1"></a>10%, a prior like <span class="in">`Beta(2, 18)`</span> would encode that honestly and cost</span>
<span id="cb15-191"><a href="#cb15-191" aria-hidden="true" tabindex="-1"></a>nothing — and with 30 people per group instead of 500, it would change the</span>
<span id="cb15-192"><a href="#cb15-192" aria-hidden="true" tabindex="-1"></a>answer materially. Chapter 14 is the version of this argument where the</span>
<span id="cb15-193"><a href="#cb15-193" aria-hidden="true" tabindex="-1"></a>prior is estimated from your own data rather than picked.</span>
<span id="cb15-194"><a href="#cb15-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-195"><a href="#cb15-195" aria-hidden="true" tabindex="-1"></a>The habit worth keeping: look at where your prior sits relative to the</span>
<span id="cb15-196"><a href="#cb15-196" aria-hidden="true" tabindex="-1"></a>answer *before* you combine them, so that if the two disagree you find out</span>
<span id="cb15-197"><a href="#cb15-197" aria-hidden="true" tabindex="-1"></a>now rather than in the meeting.</span>
<span id="cb15-198"><a href="#cb15-198" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb15-199"><a href="#cb15-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-200"><a href="#cb15-200" aria-hidden="true" tabindex="-1"></a><span class="in">```{r beta-posteriors}</span></span>
<span id="cb15-201"><a href="#cb15-201" aria-hidden="true" tabindex="-1"></a>prior_a <span class="ot">&lt;-</span> <span class="dv">2</span>; prior_b <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb15-202"><a href="#cb15-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-203"><a href="#cb15-203" aria-hidden="true" tabindex="-1"></a>posteriors <span class="ot">&lt;-</span> group_rates <span class="sc">|&gt;</span></span>
<span id="cb15-204"><a href="#cb15-204" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb15-205"><a href="#cb15-205" aria-hidden="true" tabindex="-1"></a>    <span class="at">post_alpha =</span> prior_a <span class="sc">+</span> promoted_n,</span>
<span id="cb15-206"><a href="#cb15-206" aria-hidden="true" tabindex="-1"></a>    <span class="at">post_beta  =</span> prior_b <span class="sc">+</span> (n <span class="sc">-</span> promoted_n)</span>
<span id="cb15-207"><a href="#cb15-207" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb15-208"><a href="#cb15-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-209"><a href="#cb15-209" aria-hidden="true" tabindex="-1"></a>posteriors</span>
<span id="cb15-210"><a href="#cb15-210" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-211"><a href="#cb15-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-212"><a href="#cb15-212" aria-hidden="true" tabindex="-1"></a><span class="in">```{r posterior-plot}</span></span>
<span id="cb15-213"><a href="#cb15-213" aria-hidden="true" tabindex="-1"></a>theta_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fl">0.6</span>, <span class="at">length.out =</span> <span class="dv">400</span>)</span>
<span id="cb15-214"><a href="#cb15-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-215"><a href="#cb15-215" aria-hidden="true" tabindex="-1"></a>curves <span class="ot">&lt;-</span> posteriors <span class="sc">|&gt;</span></span>
<span id="cb15-216"><a href="#cb15-216" aria-hidden="true" tabindex="-1"></a>  <span class="fu">reframe</span>(</span>
<span id="cb15-217"><a href="#cb15-217" aria-hidden="true" tabindex="-1"></a>    <span class="at">theta =</span> theta_grid,</span>
<span id="cb15-218"><a href="#cb15-218" aria-hidden="true" tabindex="-1"></a>    <span class="at">density =</span> <span class="fu">dbeta</span>(theta_grid, post_alpha, post_beta),</span>
<span id="cb15-219"><a href="#cb15-219" aria-hidden="true" tabindex="-1"></a>    <span class="at">.by =</span> label</span>
<span id="cb15-220"><a href="#cb15-220" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb15-221"><a href="#cb15-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-222"><a href="#cb15-222" aria-hidden="true" tabindex="-1"></a>prior_curve <span class="ot">&lt;-</span> <span class="fu">tibble</span>(                                                 <span class="co"># &lt;1&gt;</span></span>
<span id="cb15-223"><a href="#cb15-223" aria-hidden="true" tabindex="-1"></a>  <span class="at">theta =</span> theta_grid,</span>
<span id="cb15-224"><a href="#cb15-224" aria-hidden="true" tabindex="-1"></a>  <span class="at">density =</span> <span class="fu">dbeta</span>(theta_grid, prior_a, prior_b)</span>
<span id="cb15-225"><a href="#cb15-225" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-226"><a href="#cb15-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-227"><a href="#cb15-227" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(curves, <span class="fu">aes</span>(<span class="at">x =</span> theta, <span class="at">y =</span> density)) <span class="sc">+</span></span>
<span id="cb15-228"><a href="#cb15-228" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="at">data =</span> prior_curve, <span class="at">fill =</span> <span class="st">"grey85"</span>, <span class="at">colour =</span> <span class="st">"grey60"</span>,</span>
<span id="cb15-229"><a href="#cb15-229" aria-hidden="true" tabindex="-1"></a>            <span class="at">linetype =</span> <span class="st">"dotted"</span>) <span class="sc">+</span></span>
<span id="cb15-230"><a href="#cb15-230" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_area</span>(<span class="fu">aes</span>(<span class="at">fill =</span> label), <span class="at">alpha =</span> <span class="fl">0.25</span>, <span class="at">position =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb15-231"><a href="#cb15-231" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">colour =</span> label), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb15-232"><a href="#cb15-232" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Comparison group"</span> <span class="ot">=</span> navy_light,</span>
<span id="cb15-233"><a href="#cb15-233" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">"Diversity group"</span> <span class="ot">=</span> navy)) <span class="sc">+</span></span>
<span id="cb15-234"><a href="#cb15-234" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Comparison group"</span> <span class="ot">=</span> navy_light,</span>
<span id="cb15-235"><a href="#cb15-235" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"Diversity group"</span> <span class="ot">=</span> navy)) <span class="sc">+</span></span>
<span id="cb15-236"><a href="#cb15-236" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb15-237"><a href="#cb15-237" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-238"><a href="#cb15-238" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Prior and both posteriors, on one chart"</span>,</span>
<span id="cb15-239"><a href="#cb15-239" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Grey dotted = the Beta(2, 2) prior. Coloured curves = each group after seeing its data."</span>,</span>
<span id="cb15-240"><a href="#cb15-240" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Promotion rate"</span>, <span class="at">y =</span> <span class="st">"Density"</span>, <span class="at">colour =</span> <span class="cn">NULL</span>, <span class="at">fill =</span> <span class="cn">NULL</span></span>
<span id="cb15-241"><a href="#cb15-241" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-242"><a href="#cb15-242" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"top"</span>)</span>
<span id="cb15-243"><a href="#cb15-243" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-244"><a href="#cb15-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-245"><a href="#cb15-245" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>The prior drawn on the same axes as the posteriors, deliberately —</span>
<span id="cb15-246"><a href="#cb15-246" aria-hidden="true" tabindex="-1"></a>    Chapter 5's habit, and the clearest single picture of what Bayesian</span>
<span id="cb15-247"><a href="#cb15-247" aria-hidden="true" tabindex="-1"></a>    updating actually did here. The flat grey hump is what we believed</span>
<span id="cb15-248"><a href="#cb15-248" aria-hidden="true" tabindex="-1"></a>    beforehand; the two narrow spikes are what 1,100 records did to it.</span>
<span id="cb15-249"><a href="#cb15-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-250"><a href="#cb15-250" aria-hidden="true" tabindex="-1"></a>The gap between the grey and the coloured curves is the whole point of the</span>
<span id="cb15-251"><a href="#cb15-251" aria-hidden="true" tabindex="-1"></a>exercise: almost all of the information in those posteriors came from the</span>
<span id="cb15-252"><a href="#cb15-252" aria-hidden="true" tabindex="-1"></a>data, which is exactly what you want a weakly-informative prior to</span>
<span id="cb15-253"><a href="#cb15-253" aria-hidden="true" tabindex="-1"></a>produce. The gap between the two *coloured* curves is the finding, and how</span>
<span id="cb15-254"><a href="#cb15-254" aria-hidden="true" tabindex="-1"></a>much they overlap is the honest answer to "is this real."</span>
<span id="cb15-255"><a href="#cb15-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-256"><a href="#cb15-256" aria-hidden="true" tabindex="-1"></a><span class="fu">### The question a p-value doesn't answer directly: P(A beats B)</span></span>
<span id="cb15-257"><a href="#cb15-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-258"><a href="#cb15-258" aria-hidden="true" tabindex="-1"></a>This is Chapter 5's technique — subtract the draws — applied to two</span>
<span id="cb15-259"><a href="#cb15-259" aria-hidden="true" tabindex="-1"></a>Beta posteriors instead of two Normal ones. Draw many samples from</span>
<span id="cb15-260"><a href="#cb15-260" aria-hidden="true" tabindex="-1"></a>each posterior, subtract them element by element, and count how often</span>
<span id="cb15-261"><a href="#cb15-261" aria-hidden="true" tabindex="-1"></a>the difference lands above zero. Simple, and exactly what most</span>
<span id="cb15-262"><a href="#cb15-262" aria-hidden="true" tabindex="-1"></a>stakeholders actually want to know:</span>
<span id="cb15-263"><a href="#cb15-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-264"><a href="#cb15-264" aria-hidden="true" tabindex="-1"></a><span class="in">```{r p-a-beats-b}</span></span>
<span id="cb15-265"><a href="#cb15-265" aria-hidden="true" tabindex="-1"></a>n_draws <span class="ot">&lt;-</span> <span class="dv">100000</span></span>
<span id="cb15-266"><a href="#cb15-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-267"><a href="#cb15-267" aria-hidden="true" tabindex="-1"></a>samples <span class="ot">&lt;-</span> posteriors <span class="sc">|&gt;</span></span>
<span id="cb15-268"><a href="#cb15-268" aria-hidden="true" tabindex="-1"></a>  <span class="fu">reframe</span>(</span>
<span id="cb15-269"><a href="#cb15-269" aria-hidden="true" tabindex="-1"></a>    <span class="at">draw =</span> <span class="dv">1</span><span class="sc">:</span>n_draws,</span>
<span id="cb15-270"><a href="#cb15-270" aria-hidden="true" tabindex="-1"></a>    <span class="at">sample =</span> <span class="fu">rbeta</span>(n_draws, post_alpha, post_beta),</span>
<span id="cb15-271"><a href="#cb15-271" aria-hidden="true" tabindex="-1"></a>    <span class="at">.by =</span> diverse_grp</span>
<span id="cb15-272"><a href="#cb15-272" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb15-273"><a href="#cb15-273" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> diverse_grp, <span class="at">values_from =</span> sample, <span class="at">id_cols =</span> draw)</span>
<span id="cb15-274"><a href="#cb15-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-275"><a href="#cb15-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-276"><a href="#cb15-276" aria-hidden="true" tabindex="-1"></a>samples <span class="ot">&lt;-</span> samples <span class="sc">|&gt;</span></span>
<span id="cb15-277"><a href="#cb15-277" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">diff =</span> diverse_group <span class="sc">-</span> comparison_group)</span>
<span id="cb15-278"><a href="#cb15-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-279"><a href="#cb15-279" aria-hidden="true" tabindex="-1"></a>p_higher <span class="ot">&lt;-</span> <span class="fu">mean</span>(samples<span class="sc">$</span>diff <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb15-280"><a href="#cb15-280" aria-hidden="true" tabindex="-1"></a>p_higher</span>
<span id="cb15-281"><a href="#cb15-281" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-282"><a href="#cb15-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-283"><a href="#cb15-283" aria-hidden="true" tabindex="-1"></a><span class="in">```{r diff-plot}</span></span>
<span id="cb15-284"><a href="#cb15-284" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(samples, <span class="fu">aes</span>(<span class="at">x =</span> diff)) <span class="sc">+</span></span>
<span id="cb15-285"><a href="#cb15-285" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">60</span>, <span class="at">fill =</span> navy_light, <span class="at">colour =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb15-286"><a href="#cb15-286" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> red) <span class="sc">+</span></span>
<span id="cb15-287"><a href="#cb15-287" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb15-288"><a href="#cb15-288" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-289"><a href="#cb15-289" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Posterior distribution of the difference in promotion rates"</span>,</span>
<span id="cb15-290"><a href="#cb15-290" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">paste0</span>(<span class="st">"Red dashed = no difference. P(difference &gt; 0) = "</span>,</span>
<span id="cb15-291"><a href="#cb15-291" aria-hidden="true" tabindex="-1"></a>                      scales<span class="sc">::</span><span class="fu">percent</span>(p_higher, <span class="at">accuracy =</span> <span class="fl">0.1</span>)),</span>
<span id="cb15-292"><a href="#cb15-292" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Difference in promotion rate (diversity group − comparison group)"</span>,</span>
<span id="cb15-293"><a href="#cb15-293" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Posterior draws"</span></span>
<span id="cb15-294"><a href="#cb15-294" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb15-295"><a href="#cb15-295" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-296"><a href="#cb15-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-297"><a href="#cb15-297" aria-hidden="true" tabindex="-1"></a><span class="in">```{r credible-interval-diff}</span></span>
<span id="cb15-298"><a href="#cb15-298" aria-hidden="true" tabindex="-1"></a>diff_ci <span class="ot">&lt;-</span> <span class="fu">quantile</span>(samples<span class="sc">$</span>diff, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span>))</span>
<span id="cb15-299"><a href="#cb15-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-300"><a href="#cb15-300" aria-hidden="true" tabindex="-1"></a>diff_ci</span>
<span id="cb15-301"><a href="#cb15-301" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-302"><a href="#cb15-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-303"><a href="#cb15-303" aria-hidden="true" tabindex="-1"></a>Those three numbers are the finding, so here they are in the form you'd</span>
<span id="cb15-304"><a href="#cb15-304" aria-hidden="true" tabindex="-1"></a>actually say them — the difference in **percentage points**, which is the</span>
<span id="cb15-305"><a href="#cb15-305" aria-hidden="true" tabindex="-1"></a>unit a stakeholder thinks in:</span>
<span id="cb15-306"><a href="#cb15-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-307"><a href="#cb15-307" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **The diversity group's promotion rate is</span></span>
<span id="cb15-308"><a href="#cb15-308" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; </span><span class="in">`r scales::percent(diff_ci[[2]], accuracy = 0.1)`</span><span class="at"> different from the</span></span>
<span id="cb15-309"><a href="#cb15-309" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; comparison group's, with a 95% credible interval running from</span></span>
<span id="cb15-310"><a href="#cb15-310" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; </span><span class="in">`r scales::percent(diff_ci[[1]], accuracy = 0.1)`</span><span class="at"> to</span></span>
<span id="cb15-311"><a href="#cb15-311" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; </span><span class="in">`r scales::percent(diff_ci[[3]], accuracy = 0.1)`</span><span class="at">. The probability the</span></span>
<span id="cb15-312"><a href="#cb15-312" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; diversity group's underlying rate is genuinely higher is</span></span>
<span id="cb15-313"><a href="#cb15-313" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; </span><span class="in">`r scales::percent(p_higher, accuracy = 0.1)`</span><span class="at">.**</span></span>
<span id="cb15-314"><a href="#cb15-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-315"><a href="#cb15-315" aria-hidden="true" tabindex="-1"></a>Read the interval before the probability. If it straddles zero, the</span>
<span id="cb15-316"><a href="#cb15-316" aria-hidden="true" tabindex="-1"></a>probability statement is telling you which side of the fence the bulk of</span>
<span id="cb15-317"><a href="#cb15-317" aria-hidden="true" tabindex="-1"></a>the posterior sits on — not that a difference has been established.</span>
<span id="cb15-318"><a href="#cb15-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-319"><a href="#cb15-319" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb15-320"><a href="#cb15-320" aria-hidden="true" tabindex="-1"></a><span class="fu">## Two workflow steps that legitimately don't apply here</span></span>
<span id="cb15-321"><a href="#cb15-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-322"><a href="#cb15-322" aria-hidden="true" tabindex="-1"></a>Chapter 10's nine steps include diagnosing the sampler (step 6) and a</span>
<span id="cb15-323"><a href="#cb15-323" aria-hidden="true" tabindex="-1"></a>posterior predictive check (step 7), and this chapter does neither. That's</span>
<span id="cb15-324"><a href="#cb15-324" aria-hidden="true" tabindex="-1"></a>correct, and worth being explicit about so it doesn't read as a shortcut.</span>
<span id="cb15-325"><a href="#cb15-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-326"><a href="#cb15-326" aria-hidden="true" tabindex="-1"></a>**There is no sampler to diagnose.** A Beta prior updated by binomial data</span>
<span id="cb15-327"><a href="#cb15-327" aria-hidden="true" tabindex="-1"></a>gives a Beta posterior *exactly* — that's what "conjugate" means. <span class="in">`rbeta()`</span></span>
<span id="cb15-328"><a href="#cb15-328" aria-hidden="true" tabindex="-1"></a>above is drawing from a distribution we already know in closed form, not</span>
<span id="cb15-329"><a href="#cb15-329" aria-hidden="true" tabindex="-1"></a>exploring an unknown posterior by MCMC. There is no <span class="in">`Rhat`</span>, because there</span>
<span id="cb15-330"><a href="#cb15-330" aria-hidden="true" tabindex="-1"></a>are no chains that could fail to agree.</span>
<span id="cb15-331"><a href="#cb15-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-332"><a href="#cb15-332" aria-hidden="true" tabindex="-1"></a>**The posterior predictive check is nearly trivial.** With two groups, two</span>
<span id="cb15-333"><a href="#cb15-333" aria-hidden="true" tabindex="-1"></a>counts and two denominators, the model has as many parameters as it has</span>
<span id="cb15-334"><a href="#cb15-334" aria-hidden="true" tabindex="-1"></a>data points to reproduce. It will match the observed promotion counts</span>
<span id="cb15-335"><a href="#cb15-335" aria-hidden="true" tabindex="-1"></a>essentially by construction, so a check that it does tells you nothing.</span>
<span id="cb15-336"><a href="#cb15-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-337"><a href="#cb15-337" aria-hidden="true" tabindex="-1"></a>The general lesson, which arrives properly in Chapter 21: the workflow is a</span>
<span id="cb15-338"><a href="#cb15-338" aria-hidden="true" tabindex="-1"></a>checklist, not a ritual. Skipping a step because it cannot inform you is</span>
<span id="cb15-339"><a href="#cb15-339" aria-hidden="true" tabindex="-1"></a>different from skipping it because you didn't get round to it — and the</span>
<span id="cb15-340"><a href="#cb15-340" aria-hidden="true" tabindex="-1"></a>difference is that you can say which one you did.</span>
<span id="cb15-341"><a href="#cb15-341" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb15-342"><a href="#cb15-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-343"><a href="#cb15-343" aria-hidden="true" tabindex="-1"></a>::: callout-important</span>
<span id="cb15-344"><a href="#cb15-344" aria-hidden="true" tabindex="-1"></a><span class="fu">## Reporting this properly</span></span>
<span id="cb15-345"><a href="#cb15-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-346"><a href="#cb15-346" aria-hidden="true" tabindex="-1"></a>Report **three things together**, not a single number: the probability</span>
<span id="cb15-347"><a href="#cb15-347" aria-hidden="true" tabindex="-1"></a>the groups genuinely differ (<span class="in">`r scales::percent(p_higher, accuracy = 0.1)`</span></span>
<span id="cb15-348"><a href="#cb15-348" aria-hidden="true" tabindex="-1"></a>here), the likely *size* of the difference (the credible interval), and</span>
<span id="cb15-349"><a href="#cb15-349" aria-hidden="true" tabindex="-1"></a>whether that size is big enough to matter for a real decision. A</span>
<span id="cb15-350"><a href="#cb15-350" aria-hidden="true" tabindex="-1"></a>99%-confident but tiny difference and an 80%-confident but large one</span>
<span id="cb15-351"><a href="#cb15-351" aria-hidden="true" tabindex="-1"></a>often call for different actions — collapsing both into "significant /</span>
<span id="cb15-352"><a href="#cb15-352" aria-hidden="true" tabindex="-1"></a>not significant" throws that distinction away.</span>
<span id="cb15-353"><a href="#cb15-353" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb15-354"><a href="#cb15-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-355"><a href="#cb15-355" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb15-356"><a href="#cb15-356" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-357"><a href="#cb15-357" aria-hidden="true" tabindex="-1"></a><span class="fu">## Is the difference big enough to act on?</span></span>
<span id="cb15-358"><a href="#cb15-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-359"><a href="#cb15-359" aria-hidden="true" tabindex="-1"></a>A **region of practical equivalence (ROPE)** makes this explicit: pick</span>
<span id="cb15-360"><a href="#cb15-360" aria-hidden="true" tabindex="-1"></a>the smallest difference in promotion rate you'd actually consider</span>
<span id="cb15-361"><a href="#cb15-361" aria-hidden="true" tabindex="-1"></a>meaningful (say, 3 percentage points), and ask how much of the</span>
<span id="cb15-362"><a href="#cb15-362" aria-hidden="true" tabindex="-1"></a>posterior falls outside it.</span>
<span id="cb15-363"><a href="#cb15-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-364"><a href="#cb15-364" aria-hidden="true" tabindex="-1"></a><span class="in">```{r rope}</span></span>
<span id="cb15-365"><a href="#cb15-365" aria-hidden="true" tabindex="-1"></a>rope_width <span class="ot">&lt;-</span> <span class="fl">0.03</span></span>
<span id="cb15-366"><a href="#cb15-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-367"><a href="#cb15-367" aria-hidden="true" tabindex="-1"></a>rope_result <span class="ot">&lt;-</span> samples <span class="sc">|&gt;</span></span>
<span id="cb15-368"><a href="#cb15-368" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb15-369"><a href="#cb15-369" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_practically_higher =</span> <span class="fu">mean</span>(diff <span class="sc">&gt;</span> rope_width),</span>
<span id="cb15-370"><a href="#cb15-370" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_practically_lower  =</span> <span class="fu">mean</span>(diff <span class="sc">&lt;</span> <span class="sc">-</span>rope_width),</span>
<span id="cb15-371"><a href="#cb15-371" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_practically_equivalent =</span> <span class="fu">mean</span>(<span class="fu">abs</span>(diff) <span class="sc">&lt;=</span> rope_width)</span>
<span id="cb15-372"><a href="#cb15-372" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb15-373"><a href="#cb15-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-374"><a href="#cb15-374" aria-hidden="true" tabindex="-1"></a>rope_result</span>
<span id="cb15-375"><a href="#cb15-375" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-376"><a href="#cb15-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-377"><a href="#cb15-377" aria-hidden="true" tabindex="-1"></a><span class="in">```{r rope-plot}</span></span>
<span id="cb15-378"><a href="#cb15-378" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: true</span></span>
<span id="cb15-379"><a href="#cb15-379" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(samples, <span class="fu">aes</span>(<span class="at">x =</span> diff)) <span class="sc">+</span></span>
<span id="cb15-380"><a href="#cb15-380" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">60</span>, <span class="at">fill =</span> navy_light, <span class="at">colour =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb15-381"><a href="#cb15-381" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"rect"</span>, <span class="at">xmin =</span> <span class="sc">-</span>rope_width, <span class="at">xmax =</span> rope_width,</span>
<span id="cb15-382"><a href="#cb15-382" aria-hidden="true" tabindex="-1"></a>           <span class="at">ymin =</span> <span class="sc">-</span><span class="cn">Inf</span>, <span class="at">ymax =</span> <span class="cn">Inf</span>, <span class="at">fill =</span> <span class="st">"grey50"</span>, <span class="at">alpha =</span> <span class="fl">0.18</span>) <span class="sc">+</span>   <span class="co"># &lt;1&gt;</span></span>
<span id="cb15-383"><a href="#cb15-383" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">c</span>(<span class="sc">-</span>rope_width, rope_width),</span>
<span id="cb15-384"><a href="#cb15-384" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> red) <span class="sc">+</span></span>
<span id="cb15-385"><a href="#cb15-385" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb15-386"><a href="#cb15-386" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-387"><a href="#cb15-387" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"The same posterior, with a region of practical equivalence"</span>,</span>
<span id="cb15-388"><a href="#cb15-388" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">paste0</span>(</span>
<span id="cb15-389"><a href="#cb15-389" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Shaded band = differences too small to act on (±3pp). "</span>,</span>
<span id="cb15-390"><a href="#cb15-390" aria-hidden="true" tabindex="-1"></a>      scales<span class="sc">::</span><span class="fu">percent</span>(rope_result<span class="sc">$</span>p_practically_equivalent, <span class="at">accuracy =</span> <span class="fl">0.1</span>),</span>
<span id="cb15-391"><a href="#cb15-391" aria-hidden="true" tabindex="-1"></a>      <span class="st">" of the posterior falls inside it."</span>),</span>
<span id="cb15-392"><a href="#cb15-392" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Difference in promotion rate"</span>, <span class="at">y =</span> <span class="st">"Posterior draws"</span></span>
<span id="cb15-393"><a href="#cb15-393" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb15-394"><a href="#cb15-394" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-395"><a href="#cb15-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-396"><a href="#cb15-396" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>The ROPE drawn as a band rather than described in a table. This is the</span>
<span id="cb15-397"><a href="#cb15-397" aria-hidden="true" tabindex="-1"></a>    chart to show a stakeholder, because it converts "is there a</span>
<span id="cb15-398"><a href="#cb15-398" aria-hidden="true" tabindex="-1"></a>    difference" into "is the difference in the zone we said we'd care</span>
<span id="cb15-399"><a href="#cb15-399" aria-hidden="true" tabindex="-1"></a>    about" — a question they set the terms of, not you.</span>
<span id="cb15-400"><a href="#cb15-400" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-401"><a href="#cb15-401" aria-hidden="true" tabindex="-1"></a>Read the three numbers as a set that has to add to one. The two outer</span>
<span id="cb15-402"><a href="#cb15-402" aria-hidden="true" tabindex="-1"></a>columns are the probability the difference is **big enough to matter** in</span>
<span id="cb15-403"><a href="#cb15-403" aria-hidden="true" tabindex="-1"></a>each direction; the middle column is the probability it is real but too</span>
<span id="cb15-404"><a href="#cb15-404" aria-hidden="true" tabindex="-1"></a>small to act on, or absent altogether.</span>
<span id="cb15-405"><a href="#cb15-405" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-406"><a href="#cb15-406" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **</span><span class="in">`r scales::percent(rope_result$p_practically_equivalent, accuracy = 1)`</span></span>
<span id="cb15-407"><a href="#cb15-407" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; of the posterior falls inside ±3 percentage points — the range we agreed</span></span>
<span id="cb15-408"><a href="#cb15-408" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; in advance was too small to change anything. The probability the gap is</span></span>
<span id="cb15-409"><a href="#cb15-409" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; larger than that in either direction is</span></span>
<span id="cb15-410"><a href="#cb15-410" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; </span><span class="in">`r scales::percent(rope_result$p_practically_higher + rope_result$p_practically_lower, accuracy = 1)`</span><span class="at">.**</span></span>
<span id="cb15-411"><a href="#cb15-411" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-412"><a href="#cb15-412" aria-hidden="true" tabindex="-1"></a>This reframes "is there a difference" as "is there a difference big</span>
<span id="cb15-413"><a href="#cb15-413" aria-hidden="true" tabindex="-1"></a>enough to be worth acting on" — usually the actual question behind the</span>
<span id="cb15-414"><a href="#cb15-414" aria-hidden="true" tabindex="-1"></a>request. The critical procedural point: **pick the ROPE width before you</span>
<span id="cb15-415"><a href="#cb15-415" aria-hidden="true" tabindex="-1"></a>see the posterior.** Choosing it afterwards, once you know where the</span>
<span id="cb15-416"><a href="#cb15-416" aria-hidden="true" tabindex="-1"></a>distribution sits, is p-hacking with different vocabulary.</span>
<span id="cb15-417"><a href="#cb15-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-418"><a href="#cb15-418" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb15-419"><a href="#cb15-419" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-420"><a href="#cb15-420" aria-hidden="true" tabindex="-1"></a><span class="fu">## How this compares to other approaches</span></span>
<span id="cb15-421"><a href="#cb15-421" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-422"><a href="#cb15-422" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb15-423"><a href="#cb15-423" aria-hidden="true" tabindex="-1"></a><span class="fu">## A different lens: the classical two-proportion test</span></span>
<span id="cb15-424"><a href="#cb15-424" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-425"><a href="#cb15-425" aria-hidden="true" tabindex="-1"></a><span class="in">`prop.test()`</span> or a chi-square test asks: *if the two groups truly had</span>
<span id="cb15-426"><a href="#cb15-426" aria-hidden="true" tabindex="-1"></a>the same promotion rate, how unusual would data this different be?*</span>
<span id="cb15-427"><a href="#cb15-427" aria-hidden="true" tabindex="-1"></a>— producing a p-value. The Bayesian version above asks the question</span>
<span id="cb15-428"><a href="#cb15-428" aria-hidden="true" tabindex="-1"></a>most stakeholders actually mean when they say "is this real": *given</span>
<span id="cb15-429"><a href="#cb15-429" aria-hidden="true" tabindex="-1"></a>the data we've seen, how likely is it that the rates genuinely</span>
<span id="cb15-430"><a href="#cb15-430" aria-hidden="true" tabindex="-1"></a>differ, and by how much?* With the sample sizes typical of People</span>
<span id="cb15-431"><a href="#cb15-431" aria-hidden="true" tabindex="-1"></a>Analytics work, the two methods usually agree on direction; the</span>
<span id="cb15-432"><a href="#cb15-432" aria-hidden="true" tabindex="-1"></a>Bayesian version's edge is answering the second, size-and-confidence</span>
<span id="cb15-433"><a href="#cb15-433" aria-hidden="true" tabindex="-1"></a>question directly, in one step, without a separate power calculation.</span>
<span id="cb15-434"><a href="#cb15-434" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb15-435"><a href="#cb15-435" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-436"><a href="#cb15-436" aria-hidden="true" tabindex="-1"></a><span class="in">```{r classical-comparison}</span></span>
<span id="cb15-437"><a href="#cb15-437" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x =</span> group_rates<span class="sc">$</span>promoted_n, <span class="at">n =</span> group_rates<span class="sc">$</span>n)</span>
<span id="cb15-438"><a href="#cb15-438" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb15-439"><a href="#cb15-439" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-440"><a href="#cb15-440" aria-hidden="true" tabindex="-1"></a>Worth reading against the Bayesian output above, line by line, because the</span>
<span id="cb15-441"><a href="#cb15-441" aria-hidden="true" tabindex="-1"></a>two are closer than the philosophical argument suggests:</span>
<span id="cb15-442"><a href="#cb15-442" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-443"><a href="#cb15-443" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**`p-value`** — the probability of seeing a gap at least this large *if</span>
<span id="cb15-444"><a href="#cb15-444" aria-hidden="true" tabindex="-1"></a>  the two rates were truly identical*. Note the direction of that</span>
<span id="cb15-445"><a href="#cb15-445" aria-hidden="true" tabindex="-1"></a>  sentence. It is not the probability that the rates are the same, and it</span>
<span id="cb15-446"><a href="#cb15-446" aria-hidden="true" tabindex="-1"></a>  is not the probability the gap is real, which is what</span>
<span id="cb15-447"><a href="#cb15-447" aria-hidden="true" tabindex="-1"></a>  <span class="in">`r scales::percent(p_higher, accuracy = 0.1)`</span> above actually gives you.</span>
<span id="cb15-448"><a href="#cb15-448" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**`95 percent confidence interval`** — compare it directly to the</span>
<span id="cb15-449"><a href="#cb15-449" aria-hidden="true" tabindex="-1"></a>  credible interval from <span class="in">`quantile(samples$diff, ...)`</span>. With hundreds of</span>
<span id="cb15-450"><a href="#cb15-450" aria-hidden="true" tabindex="-1"></a>  observations per group and a weak prior, the two will land in nearly the</span>
<span id="cb15-451"><a href="#cb15-451" aria-hidden="true" tabindex="-1"></a>  same place, which is the honest version of "these methods usually</span>
<span id="cb15-452"><a href="#cb15-452" aria-hidden="true" tabindex="-1"></a>  agree." What differs is what you're allowed to say about the interval:</span>
<span id="cb15-453"><a href="#cb15-453" aria-hidden="true" tabindex="-1"></a>  the credible interval is a statement about where the difference probably</span>
<span id="cb15-454"><a href="#cb15-454" aria-hidden="true" tabindex="-1"></a>  is, the confidence interval is a statement about the procedure that</span>
<span id="cb15-455"><a href="#cb15-455" aria-hidden="true" tabindex="-1"></a>  produced it.</span>
<span id="cb15-456"><a href="#cb15-456" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**`sample estimates`** — the two raw rates, unchanged from</span>
<span id="cb15-457"><a href="#cb15-457" aria-hidden="true" tabindex="-1"></a>  <span class="in">`group_rates`</span>. No shrinkage, no prior, no pooling.</span>
<span id="cb15-458"><a href="#cb15-458" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-459"><a href="#cb15-459" aria-hidden="true" tabindex="-1"></a>The one thing <span class="in">`prop.test()`</span> does not give you at all is the ROPE question.</span>
<span id="cb15-460"><a href="#cb15-460" aria-hidden="true" tabindex="-1"></a>There is no way to ask it "how likely is the gap bigger than three</span>
<span id="cb15-461"><a href="#cb15-461" aria-hidden="true" tabindex="-1"></a>percentage points," because it only ever tests against exactly zero.</span>
<span id="cb15-462"><a href="#cb15-462" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-463"><a href="#cb15-463" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb15-464"><a href="#cb15-464" aria-hidden="true" tabindex="-1"></a><span class="fu">## Why this book uses estimation, not Bayes Factors, for this kind of test</span></span>
<span id="cb15-465"><a href="#cb15-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-466"><a href="#cb15-466" aria-hidden="true" tabindex="-1"></a>Keith McNulty's book covers **Bayesian hypothesis testing** using</span>
<span id="cb15-467"><a href="#cb15-467" aria-hidden="true" tabindex="-1"></a>**Bayes Factors** — comparing the evidence for "the rates are equal"</span>
<span id="cb15-468"><a href="#cb15-468" aria-hidden="true" tabindex="-1"></a>against "the rates differ" as a ratio, the Bayesian analogue of a</span>
<span id="cb15-469"><a href="#cb15-469" aria-hidden="true" tabindex="-1"></a>p-value-producing test. It's a legitimate and well-developed approach,</span>
<span id="cb15-470"><a href="#cb15-470" aria-hidden="true" tabindex="-1"></a>useful in particular when the actual question is *"is there truly a</span>
<span id="cb15-471"><a href="#cb15-471" aria-hidden="true" tabindex="-1"></a>non-zero effect at all?"* — common in scientific replication contexts,</span>
<span id="cb15-472"><a href="#cb15-472" aria-hidden="true" tabindex="-1"></a>and covered in his Chapter 12. This book leans instead on the</span>
<span id="cb15-473"><a href="#cb15-473" aria-hidden="true" tabindex="-1"></a>estimation approach above (posteriors, credible intervals, and a ROPE),</span>
<span id="cb15-474"><a href="#cb15-474" aria-hidden="true" tabindex="-1"></a>because the questions People Analytics usually needs answered are</span>
<span id="cb15-475"><a href="#cb15-475" aria-hidden="true" tabindex="-1"></a>"how big" and "are we confident enough to act," not "is the effect</span>
<span id="cb15-476"><a href="#cb15-476" aria-hidden="true" tabindex="-1"></a>exactly zero" — and estimation answers those directly, in the same</span>
<span id="cb15-477"><a href="#cb15-477" aria-hidden="true" tabindex="-1"></a>units as the decision. Bayes Factors can also be sensitive to exactly</span>
<span id="cb15-478"><a href="#cb15-478" aria-hidden="true" tabindex="-1"></a>how you specify the alternative hypothesis, which adds a layer of</span>
<span id="cb15-479"><a href="#cb15-479" aria-hidden="true" tabindex="-1"></a>judgment estimation avoids. Neither is "the correct Bayesian method" —</span>
<span id="cb15-480"><a href="#cb15-480" aria-hidden="true" tabindex="-1"></a>pick the one that matches the actual question.</span>
<span id="cb15-481"><a href="#cb15-481" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb15-482"><a href="#cb15-482" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-483"><a href="#cb15-483" aria-hidden="true" tabindex="-1"></a>::: callout-tip</span>
<span id="cb15-484"><a href="#cb15-484" aria-hidden="true" tabindex="-1"></a><span class="fu">## For the ML/DS crowd</span></span>
<span id="cb15-485"><a href="#cb15-485" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-486"><a href="#cb15-486" aria-hidden="true" tabindex="-1"></a>If you've heard of **Thompson sampling** or **multi-armed bandits** —</span>
<span id="cb15-487"><a href="#cb15-487" aria-hidden="true" tabindex="-1"></a>used in live experimentation platforms and recommender systems to</span>
<span id="cb15-488"><a href="#cb15-488" aria-hidden="true" tabindex="-1"></a>decide which variant to show next — you've seen this exact method</span>
<span id="cb15-489"><a href="#cb15-489" aria-hidden="true" tabindex="-1"></a>running continuously. Thompson sampling literally draws one sample</span>
<span id="cb15-490"><a href="#cb15-490" aria-hidden="true" tabindex="-1"></a>from each arm's Beta posterior and picks whichever arm's sample is</span>
<span id="cb15-491"><a href="#cb15-491" aria-hidden="true" tabindex="-1"></a>highest, repeating as data arrives; it's the sequential, automated</span>
<span id="cb15-492"><a href="#cb15-492" aria-hidden="true" tabindex="-1"></a>sibling of the one-shot comparison in this chapter. The maths is</span>
<span id="cb15-493"><a href="#cb15-493" aria-hidden="true" tabindex="-1"></a>identical — sampling from Beta posteriors and comparing — just wired</span>
<span id="cb15-494"><a href="#cb15-494" aria-hidden="true" tabindex="-1"></a>into a live decision loop instead of a one-time analysis.</span>
<span id="cb15-495"><a href="#cb15-495" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb15-496"><a href="#cb15-496" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-497"><a href="#cb15-497" aria-hidden="true" tabindex="-1"></a>::: callout-caution</span>
<span id="cb15-498"><a href="#cb15-498" aria-hidden="true" tabindex="-1"></a><span class="fu">## Try it yourself</span></span>
<span id="cb15-499"><a href="#cb15-499" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-500"><a href="#cb15-500" aria-hidden="true" tabindex="-1"></a>Rerun this comparison for <span class="in">`flexible`</span> vs. not, and separately for</span>
<span id="cb15-501"><a href="#cb15-501" aria-hidden="true" tabindex="-1"></a><span class="in">`store`</span> vs. not. Do either of those produce a clearer signal than</span>
<span id="cb15-502"><a href="#cb15-502" aria-hidden="true" tabindex="-1"></a><span class="in">`diverse`</span> did? Report your answer the way you would to a stakeholder —</span>
<span id="cb15-503"><a href="#cb15-503" aria-hidden="true" tabindex="-1"></a>probability of a real difference, likely size, and whether it clears</span>
<span id="cb15-504"><a href="#cb15-504" aria-hidden="true" tabindex="-1"></a>your ROPE.</span>
<span id="cb15-505"><a href="#cb15-505" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb15-506"><a href="#cb15-506" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-507"><a href="#cb15-507" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb15-508"><a href="#cb15-508" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-509"><a href="#cb15-509" aria-hidden="true" tabindex="-1"></a><span class="fu">## On the job {.unnumbered}</span></span>
<span id="cb15-510"><a href="#cb15-510" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-511"><a href="#cb15-511" aria-hidden="true" tabindex="-1"></a>::: callout-important</span>
<span id="cb15-512"><a href="#cb15-512" aria-hidden="true" tabindex="-1"></a><span class="fu">## Why this matters day to day</span></span>
<span id="cb15-513"><a href="#cb15-513" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-514"><a href="#cb15-514" aria-hidden="true" tabindex="-1"></a>Most People Analytics "did X work" questions are exactly this shape —</span>
<span id="cb15-515"><a href="#cb15-515" aria-hidden="true" tabindex="-1"></a>two groups, a rate, and a decision to make with a modest sample. This</span>
<span id="cb15-516"><a href="#cb15-516" aria-hidden="true" tabindex="-1"></a>method scales down gracefully to small groups (unlike a chi-square test,</span>
<span id="cb15-517"><a href="#cb15-517" aria-hidden="true" tabindex="-1"></a>which gets unreliable with few observations per cell), gives you a</span>
<span id="cb15-518"><a href="#cb15-518" aria-hidden="true" tabindex="-1"></a>direct, presentable probability statement, and — via the ROPE — keeps</span>
<span id="cb15-519"><a href="#cb15-519" aria-hidden="true" tabindex="-1"></a>you honest about the difference between "statistically distinguishable"</span>
<span id="cb15-520"><a href="#cb15-520" aria-hidden="true" tabindex="-1"></a>and "big enough to matter."</span>
<span id="cb15-521"><a href="#cb15-521" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb15-522"><a href="#cb15-522" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-523"><a href="#cb15-523" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb15-524"><a href="#cb15-524" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-525"><a href="#cb15-525" aria-hidden="true" tabindex="-1"></a><span class="fu">## Summary {.unnumbered}</span></span>
<span id="cb15-526"><a href="#cb15-526" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-527"><a href="#cb15-527" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb15-528"><a href="#cb15-528" aria-hidden="true" tabindex="-1"></a><span class="fu">## Today you learned</span></span>
<span id="cb15-529"><a href="#cb15-529" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-530"><a href="#cb15-530" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>A Bayesian A/B test puts a Beta posterior on each group's rate and</span>
<span id="cb15-531"><a href="#cb15-531" aria-hidden="true" tabindex="-1"></a>    compares them **directly by sampling**, rather than via a</span>
<span id="cb15-532"><a href="#cb15-532" aria-hidden="true" tabindex="-1"></a>    significance test.</span>
<span id="cb15-533"><a href="#cb15-533" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>**P(A beats B)** and the **credible interval on the difference**</span>
<span id="cb15-534"><a href="#cb15-534" aria-hidden="true" tabindex="-1"></a>    together answer "is it real" and "how big," in one step.</span>
<span id="cb15-535"><a href="#cb15-535" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>A **ROPE** turns "is there a difference" into the more useful "is</span>
<span id="cb15-536"><a href="#cb15-536" aria-hidden="true" tabindex="-1"></a>    the difference big enough to act on."</span>
<span id="cb15-537"><a href="#cb15-537" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span>This book favours estimation over Bayes-Factor hypothesis testing</span>
<span id="cb15-538"><a href="#cb15-538" aria-hidden="true" tabindex="-1"></a>    for exactly this kind of question — see the note above for when</span>
<span id="cb15-539"><a href="#cb15-539" aria-hidden="true" tabindex="-1"></a>    you'd reach for the other approach instead.</span>
<span id="cb15-540"><a href="#cb15-540" aria-hidden="true" tabindex="-1"></a><span class="ss">5.  </span>Comparisons involving protected characteristics need the same care</span>
<span id="cb15-541"><a href="#cb15-541" aria-hidden="true" tabindex="-1"></a>    as the pay analysis in Chapter 16 — a statistical signal, not a</span>
<span id="cb15-542"><a href="#cb15-542" aria-hidden="true" tabindex="-1"></a>    complete equity conclusion on its own.</span>
<span id="cb15-543"><a href="#cb15-543" aria-hidden="true" tabindex="-1"></a><span class="ss">6.  </span>The **arithmetic is the same whether or not anyone was randomised, and</span>
<span id="cb15-544"><a href="#cb15-544" aria-hidden="true" tabindex="-1"></a>    the licence to interpret it isn't.** With random assignment this is a</span>
<span id="cb15-545"><a href="#cb15-545" aria-hidden="true" tabindex="-1"></a>    causal answer; without it — as in this chapter's worked example — it</span>
<span id="cb15-546"><a href="#cb15-546" aria-hidden="true" tabindex="-1"></a>    is an accurate description of a difference whose cause is still open,</span>
<span id="cb15-547"><a href="#cb15-547" aria-hidden="true" tabindex="-1"></a>    and Chapters 21 and 22 are what you reach for next.</span>
<span id="cb15-548"><a href="#cb15-548" aria-hidden="true" tabindex="-1"></a><span class="ss">7.  </span>Set the **ROPE width before you look at the posterior**. Choosing it</span>
<span id="cb15-549"><a href="#cb15-549" aria-hidden="true" tabindex="-1"></a>    afterwards is p-hacking in different clothes.</span>
<span id="cb15-550"><a href="#cb15-550" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb15-551"><a href="#cb15-551" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-552"><a href="#cb15-552" aria-hidden="true" tabindex="-1"></a><span class="fu">## Next chapter {.unnumbered}</span></span>
<span id="cb15-553"><a href="#cb15-553" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-554"><a href="#cb15-554" aria-hidden="true" tabindex="-1"></a>**Causal structure: drawing the graph** — an A/B test is the easy case,</span>
<span id="cb15-555"><a href="#cb15-555" aria-hidden="true" tabindex="-1"></a>because you controlled who went into which group. The next two chapters</span>
<span id="cb15-556"><a href="#cb15-556" aria-hidden="true" tabindex="-1"></a>are about the far more common situation where you didn't, and what can</span>
<span id="cb15-557"><a href="#cb15-557" aria-hidden="true" tabindex="-1"></a>still be said.</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Bayesian Thinking for People Analytics</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>