{
  "hash": "1e42553252bbc09cb4b6514ce9b320f6",
  "result": {
    "engine": "knitr",
    "markdown": "# When Data Has Structure: Multilevel Models\n\n## Welcome back {.unnumbered}\n\nPeople Analytics data is almost always **grouped**: employees within\nmanagers, managers within offices, survey responses within teams,\nperformance within business units.\n\n::: callout-important\nObservations in the same group resemble each other. Pretending they're\nindependent makes you **overconfident** — and a sceptical stakeholder\nnotices.\n:::\n\n### The league table {.unnumbered}\n\nHere is a thing that happens in every organisation, probably this\nquarter.\n\nSomeone runs the numbers on manager assessment scores by office, sorts\nthem descending, and puts the table on a slide. The top office gets\npraised and asked to share what it's doing. The bottom office gets a\ndevelopment plan, or a visit.\n\nThe table is arithmetically correct. Every average in it is computed\nproperly. And it is very likely to be close to meaningless, because\n**a league table of group averages is partly a league table of group\nsizes** — the smaller the office, the further from the middle its\naverage can wander for no reason at all.\n\nYou already know why. Chapter 3 showed that an estimate from a small\nsample swings wildly, and Chapter 1 named the trap this creates: the\nextreme office regresses to the mean next year, and whatever\nintervention happened in between gets the credit.\n\n::: callout-note\nSo the honest question isn't *\"which office is best?\"* It's **\"how\nmuch of this ranking is real, and how much is sample size?\"** — and\nthat question has a proper answer.\n:::\n\nToday we handle grouped data with a **multilevel model**, and meet one\nof the most elegant ideas in statistics: **partial pooling**. It's the\nfoundation for Chapters 14, 15 and 16, which are the chapters most\nPeople Analytics teams end up needing.\n\nWe switch to the `managers` dataset: manager test scores, grouped by\ncity.\n\n## What you'll be able to do by the end {.unnumbered}\n\n1.  Recognise **hierarchically structured** data, and why ignoring the\n    structure makes you overconfident\n2.  Explain **complete pooling, no pooling, and partial pooling** —\n    and why the third is almost always right\n3.  Fit a **varying-intercepts** model with `brms`\n4.  See **shrinkage** happen, and explain to a stakeholder why the\n    small office moved\n5.  Answer the \"shouldn't you correct for **multiple comparisons**?\"\n    challenge, and know exactly how far the answer goes\n6.  Read the **group-level** (hyper)parameters, including one that is\n    a business finding in its own right\n7.  Predict for a group you have **no data on at all**\n\n------------------------------------------------------------------------\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(peopleanalyticsdata)\nlibrary(brms)\nlibrary(tidybayes)\n\ntheme_set(theme_minimal(base_size = 13))\nset.seed(2026)\n\ndata(\"managers\", package = \"peopleanalyticsdata\")\n\n# Drop rows missing either variable we're about to model, following the\n# check-before-you-summarise habit from Chapter 1.\nmanagers <- managers |> drop_na(test_score, city)\n```\n:::\n\n\n`managers` has 571 managers, one row each, with a `test_score` (a score\non a standard assessment given to all managers) and `city` (their\noffice location) — exactly the grouped shape we need.\n\n### Look at the scale before you choose a prior {.unnumbered}\n\nChapter 5's rule was never to write a prior for a variable you haven't\nlooked at. `test_score` is on an unfamiliar scale, so:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmanagers |>\n  summarise(\n    n      = n(),\n    mean   = mean(test_score),\n    sd     = sd(test_score),\n    lowest = min(test_score),\n    highest = max(test_score)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    n     mean       sd lowest highest\n1 571 240.1716 80.04233      0     500\n```\n\n\n:::\n:::\n\n\nScores run in the hundreds, not the tens — worth thirty seconds of\nchecking, because a prior written for the wrong order of magnitude\nwill quietly fight the data and produce a badly-behaved model.\n\nI always plot the variable as well as summarising it. Summary\nstatistics tell you where a variable sits; only the picture tells you\nwhether it sits there in the way you assumed. Five numbers are\ncompatible with a great many shapes, and some of those shapes would\nchange the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(managers, aes(x = test_score)) +\n  geom_histogram(bins = 30, fill = \"#122a52\", alpha = 0.45, colour = \"white\") +\n  geom_vline(xintercept = mean(managers$test_score),\n             colour = \"#8a5a00\", linewidth = 1) +\n  geom_vline(xintercept = median(managers$test_score),\n             colour = \"#8a5a00\", linewidth = 1, linetype = \"dashed\") +\n  labs(title = \"Distribution of manager test scores\",\n       subtitle = \"Solid line = mean, dashed line = median\",\n       x = \"Test score\", y = \"Number of managers\")\n```\n\n::: {.cell-output-display}\n![](08-multilevel-models_files/figure-html/score-distribution-1.png){width=672}\n:::\n:::\n\n\nOne broad hump, mean and median close together, no second cluster and\nno wall of scores piled at a maximum. That's the shape `family =\ngaussian()` assumes, so the default choice is defensible here rather\nthan merely conventional. Had the picture shown two humps, or a hard\nceiling, or a long tail on one side, the model below would have needed\nto change — and no summary table would have told us.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npriors <- c(\n  prior(normal(200, 100),  class = Intercept),   # <1>\n  prior(exponential(0.05), class = sd),          # <2>\n  prior(exponential(0.01), class = sigma)        # <3>\n)\n```\n:::\n\n\n1.  The **grand mean** across all offices. Centred at 200 with plenty\n    of room either side — we know the scale, and little else.\n2.  How much **offices differ from each other**. Rate 0.05 means an\n    expected between-office spread of about 20 points (remember from\n    Chapter 5: the exponential's average is 1 ÷ rate). This is the new\n    parameter class in this chapter — `sd` is always the group-level\n    variation.\n3.  How much **individual managers differ within an office**. Expected\n    around 100, using the range ÷ 4 rule from Chapter 5.\n\n------------------------------------------------------------------------\n\n## The problem\n\n### Look at our cities\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- managers |>\n  group_by(city) |>\n  summarise(\n    raw_mean = mean(test_score),\n    n        = n(),\n    se       = sd(test_score) / sqrt(n())    # <1>\n  ) |>\n  arrange(n)\n\nraw\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  city          raw_mean     n    se\n  <fct>            <dbl> <int> <dbl>\n1 Orlando           213.    23 13.5 \n2 Houston           221.    25 15.4 \n3 San Francisco     244.    52 13.0 \n4 Chicago           223.    62 10.9 \n5 New York          253.   196  5.41\n6 Toronto           238.   213  5.42\n```\n\n\n:::\n:::\n\n\n1.  The standard error from Chapter 3 — σ ÷ √n. This is the column the\n    league table never has, and it's the one that decides whether the\n    ranking means anything.\n\nRead the `n` column before the `raw_mean` column. Orlando has 23\nmanagers; Toronto has 213. That is a ninefold difference in how much\nevidence sits behind each average, and nothing on the slide version of\nthis table would tell you so.\n\nNow look at `se`. Toronto's average is worth about ±5 points; Houston's\nis worth about ±15. The small offices are not slightly less reliable\nthan the large ones — they are about three times less reliable.\n\nPut the two together and the ranking starts to fall apart. New York\ntops the table at 253 and San Francisco follows at 244, a gap of nine\npoints — but San Francisco's own average carries a standard error of\n13. The bottom three offices sit at 223, 221 and 213, separated by\ngaps smaller than any of their standard errors. Most of the ordering in\nthis table is not a finding about offices. It is the arithmetic of\nunequal sample sizes.\n\n### The league table, with its error bars restored\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(raw, aes(x = raw_mean, y = fct_reorder(city, raw_mean))) +\n  geom_vline(xintercept = mean(managers$test_score),\n             linetype = \"dashed\", colour = \"#d32f2f\") +\n  geom_errorbarh(aes(xmin = raw_mean - 2 * se,\n                     xmax = raw_mean + 2 * se),\n                 height = 0.2, colour = \"#122a52\") +\n  geom_point(aes(size = n), colour = \"#122a52\") +\n  labs(title = \"The same ranking, showing what each average is worth\",\n       subtitle = \"Bars ≈ 95% range for each office average; red dashed = overall mean\",\n       x = \"Mean test score\", y = NULL, size = \"Managers\")\n```\n\n::: {.cell-output-display}\n![](08-multilevel-models_files/figure-html/raw-with-error-1.png){width=672}\n:::\n:::\n\n\n::: callout-important\n## What the error bars do to the story\n\nThe point estimates give you a clean, confident ordering. The bars\nshow most of that ordering is inside the noise — the small offices\nhave intervals wide enough to be almost anywhere, and several offices\nthat look separated on the slide have intervals that overlap heavily.\n\nTwo things follow, and they pull in the same direction:\n\n1.  **A small office's average is a weak estimate**, not a strong\n    result. A handful of unusually strong or weak test-takers moves it\n    a long way.\n2.  **Ranking amplifies exactly this.** Sorting descending puts\n    whichever group got the luckiest draw at the top, and small groups\n    get lucky more often than large ones. The top of a league table is\n    therefore *systematically* enriched with small groups — and they\n    are the ones most likely to look ordinary again next year.\n:::\n\n::: callout-note\n## Why not just drop the small offices?\n\nIt's the obvious fix and it's a bad one. You'd be discarding real\ninformation about real employees, and you'd still have to defend the\nthreshold — is 30 managers enough? 50? Whatever line you draw, an\noffice just above it gets treated as reliable and one just below gets\ndeleted from the analysis entirely.\n\nPartial pooling does something better: it keeps every office and\nweights each one by how much evidence it actually carries. Nothing is\nthrown away, and no threshold has to be defended.\n:::\n\n------------------------------------------------------------------------\n\n## Three ways to handle groups\n\n**Pooling** means combining data across groups. The question in this\nsection is how much of it to do, and there are only three answers\navailable.\n\nAt one extreme you can treat the six offices as if they were one — pool\neverything, and accept that you have thrown away the differences between\nthem. At the other you can treat each office as a separate world with\nnothing to learn from the others — pool nothing, and accept that a\n23-manager office gets the same trust as a 213-manager one.\n\nNeither is right, and the useful answer is the one in between. The rest\nof this chapter is about how a model finds it for you.\n\n### Option 1 — complete pooling\n\nOne average across all responses, used for every office.\n\n-   **Pro** — uses all the data, very stable\n-   **Con** — pretends every office is identical, which is plainly\n    false\n\n### Option 2 — no pooling\n\nA separate average for each office — the raw means above.\n\n-   **Pro** — respects that offices differ\n-   **Con** — over-trusts tiny samples; the small-n offices dominate\n    the extremes\n\n### Option 3 — partial pooling\n\n::: callout-important\nEach office gets its **own** estimate, but offices with little data are\n**pulled toward the overall average** — by an amount **the data\nitself decides**.\n:::\n\nBig offices barely move. Small ones move a lot. Nobody has to choose\nthe amount by hand.\n\n### How much does each office move?\n\nThe mechanism is worth seeing, because \"the model decides\" sounds like\nmagic and isn't. Each office's estimate is a **weighted average** of\nits own raw mean and the grand mean, and the weight on its own data is:\n\n$$w = \\frac{n}{n + \\sigma^2 / \\tau^2}$$\n\n*How much you trust an office's own average depends on how many\nmanagers it has, relative to how noisy individuals are compared with\nhow much offices genuinely differ.*\n\nRead what that does at the extremes:\n\n-   **Large *n*** → *w* approaches 1. The office keeps its own\n    average. It has earned it.\n-   **Small *n*** → *w* approaches 0. The office is pulled towards the\n    grand mean, because its own average is mostly noise.\n-   **Offices genuinely differ a lot** (large τ) → everyone keeps more\n    of their own average, because being different is expected.\n-   **Offices are all much the same** (small τ) → everyone is pulled\n    hard towards the middle, because apparent differences are\n    probably noise.\n\n::: callout-note\nThat last pair is the clever bit. The model doesn't just ask how much\ndata each office has — it also **learns from the offices collectively\nhow different offices tend to be**, and uses that to judge how\nseriously to take any individual one. No single office could work this\nout alone.\n:::\n\n------------------------------------------------------------------------\n\n## Fit a varying-intercepts model\n\nThe formula `test_score ~ 1 + (1 | city)` reads: an overall average\n(`1`), plus a **city-specific adjustment** (`(1 | city)`) drawn from a\nshared distribution across cities. Still the same `brm()`, same\n`family = gaussian()` — the only thing that's new is what's inside the\nformula.\n\nThis model introduces a genuinely new kind of prior: not just \"where's\nthe average,\" but **\"how much do groups typically vary\"** — the τ in\nthe weighting formula above. That's the `class = sd` prior we set in\nthe setup. As always, look at both before fitting:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the plotting code\"}\nbind_rows(\n  tibble(x = seq(-100, 500, length.out = 400), parameter = \"Intercept: Normal(200, 100)\") |>\n    mutate(density = dnorm(x, mean = 200, sd = 100)),\n  tibble(x = seq(0, 100, length.out = 400), parameter = \"Between-city sd: Exponential(0.05)\") |>\n    mutate(density = dexp(x, rate = 0.05))\n) |>\n  ggplot(aes(x, density)) +\n  geom_area(fill = \"#8fabd0\", alpha = 0.30) +\n  geom_line(colour = \"#8fabd0\", linewidth = 1) +\n  facet_wrap(~ parameter, scales = \"free\") +\n  labs(title = \"Our two headline priors\",\n       subtitle = \"Both on the scale the data actually lives on\",\n       x = NULL, y = \"Prior density\")\n```\n\n::: {.cell-output-display}\n![](08-multilevel-models_files/figure-html/plot-ml-priors-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_ml <- brm(\n  test_score ~ 1 + (1 | city),\n  data = managers, family = gaussian(),\n  prior = priors,\n  chains = 4, iter = 4000, seed = 8, refresh = 0,     # <1>\n  control = list(adapt_delta = 0.95)                  # <2>\n)\n\nsummary(fit_ml)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity \nFormula: test_score ~ 1 + (1 | city) \n   Data: managers (Number of observations: 571) \n  Draws: 4 chains, each with iter = 4000; warmup = 2000; thin = 1;\n         total post-warmup draws = 8000\n\nMultilevel Hyperparameters:\n~city (Number of levels: 6) \n              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsd(Intercept)    12.10      7.53     1.18    30.34 1.00     1958     2079\n\nRegression Coefficients:\n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept   236.01      7.33   219.53   249.07 1.00     2892     2990\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma    79.71      2.33    75.27    84.46 1.00     7123     5369\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n1.  Double the usual iterations. At the standard 2,000 this model\n    returns `Rhat = 1.01` on the intercept — right at the threshold the\n    diagnostics box below tells you not to accept. Six groups is a hard\n    posterior to explore, and the cheapest fix is to run longer.\n2.  The first time we've needed an extra argument beyond the standard\n    call. Multilevel models have an awkwardly shaped posterior — when\n    a group-level `sd` could plausibly be near zero, the geometry\n    narrows to a spike the sampler can overshoot, and you get\n    *divergent transition* warnings. Raising `adapt_delta` makes the\n    sampler take smaller, more careful steps. It's slower and it's the\n    standard first response. Chapter 11 explains what's actually\n    happening.\n\n    The default is **0.8**. The number is the sampler's target\n    acceptance rate: the higher it is, the smaller and more cautious\n    each step becomes, and the less likely the sampler is to overshoot\n    the narrow part of the posterior. Raising it costs time and buys\n    reliability, so the convention is to escalate only as far as you\n    need — 0.95 first, 0.99 if warnings persist. We start at 0.95 here\n    because multilevel models with few groups warn at the default often\n    enough that it is not worth running twice to find out.\n\n### Two new numbers to read\n\nThe output has grown a section. Before reading any of it as a finding,\nhere is what each block is telling you, in order of how much it matters.\n\n**`sigma`, at the bottom, is how much individual managers differ from\neach other.** About 80 points. Two managers picked at random from the\nsame office typically score around 80 points apart.\n\n**`sd(Intercept)`, at the top, is how much the offices differ.** About\n12 points. That is the number the whole league table was implicitly\nclaiming to measure.\n\n**`Intercept`, in the middle, is the average across offices** — about\n236 — now estimated properly rather than by averaging six averages of\nvery different sizes.\n\n::: callout-important\nPut the first two side by side and the chapter's argument is finished\nin one line: **differences between individual managers are roughly\nseven times larger than differences between offices.**\n\nAround 2% of the variation in test scores sits between offices. The\nother 98% sits between people working in the same office. A league\ntable of office averages is a ranking of the 2%, presented as though it\nwere the whole story.\n:::\n\nThat ratio has a name — the intraclass correlation — and Chapter 16\nturns it into a finding in its own right rather than a caveat.\n\n::: callout-note\n## `sd(Intercept)` is a real finding\n\nIt answers a genuine business question: *\"how much does manager\nassessment performance actually vary between our offices?\"* A small\nvalue means your offices are consistent and the league table was\nnoise; a large one means office genuinely matters and is worth\ninvestigating.\n\nReport it with its interval, not as a point. Which brings us to an\nhonest caveat.\n:::\n\n### Six groups is not many\n\nLook at the credible interval on `sd(Intercept)`. It runs from about\n1.5 to about 30 — the estimate is 12, and the data cannot rule out\neither \"offices are essentially identical\" or \"offices differ by 30\npoints\". That interval is enormous, and it will be, because we are\ntrying to estimate *how much offices vary* from only **six offices**.\nSix numbers is thin evidence about a spread, in exactly the way that\nChapter 3 warned a small sample would be.\n\nThis is the most common honest limitation of multilevel models in\nPeople Analytics, and it's worth stating out loud rather than hiding:\nyou often have plenty of *people* and very few *groups*. The model is\nstill the right choice — partial pooling with six groups beats both\nalternatives — but the between-group variance is the parameter you\nshould be most cautious about quoting.\n\nA rough guide: with fewer than about five groups the variance\ncomponent is barely identified and you're leaning on your prior; by\nten or fifteen it starts to firm up; with fifty you can take it\nseriously. Chapter 15 partially pools across **571 individual\nmanagers**, and the difference in precision is obvious when you get\nthere.\n\n::: callout-tip\n## Check the diagnostics here especially\n\nChapter 5 said Rhat should read 1.00 and ESS should run into the\nthousands. Multilevel models are the first place in this book where\nthat isn't automatic — the awkward geometry mentioned above makes them\ngenuinely harder to sample.\n\nIf you see `Rhat` at 1.01 or above, low `Bulk_ESS`, or divergent\ntransition warnings, **do not report the model**. Raise `adapt_delta`\ntowards 0.99, increase `iter`, and check your priors are on the right\nscale — an off-scale prior fighting the data is a common cause, and\nit's why we measured `test_score` before writing one.\n:::\n\n------------------------------------------------------------------------\n\n### Does it fit?\n\nDiagnostics said the sampler behaved. That is step 7. Step 8 asks a\ndifferent question — not *did the machinery work* but *can this model\nproduce data that looks like ours*:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(fit_ml, ndraws = 100) +\n  labs(title = \"Posterior predictive check\",\n       subtitle = \"Light lines = datasets the model would generate; dark = the real data\",\n       x = \"Test score\", y = \"Density\")\n```\n\n::: {.cell-output-display}\n![](08-multilevel-models_files/figure-html/ppc-ml-1.png){width=672}\n:::\n:::\n\n\nLook for the dark line sitting inside the light ones. A multilevel model\ncan pass every convergence check and still be the wrong shape — if test\nscores are bimodal, or bounded, or have a spike at zero, a Normal\nlikelihood will smooth straight over it and the shrinkage estimates\ninherit the error.\n\n::: callout-note\nTwo things this check will *not* tell you, and it is worth knowing the\nboundary. It does not tell you whether six groups is enough to estimate\n`sd(Intercept)` — nothing does, beyond reporting the interval, which we\ndid above. And it does not tell you whether the offices differ *because\nof* something about the offices. That is a causal question, and Chapter 21 is where it gets answered.\n:::\n\n------------------------------------------------------------------------\n\n## See the shrinkage\n\nWe're about to use `add_epred_draws()` again — the \"epred\" is\n*expected prediction*, introduced in Chapter 6 alongside\n`add_predicted_draws()`. The reminder, since it matters here: `epred`\ngives you the posterior for the **average** in each group, carrying\nonly the uncertainty in the model's parameters. `predicted` would give\nyou the range for a single new *manager*, which is much wider and is\nnot the question a league table asks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrand_mean <- mean(managers$test_score)\n\npooled <- managers |>\n  distinct(city) |>\n  add_epred_draws(fit_ml) |>\n  mean_qi(.epred)\n\ncompare <- left_join(raw, pooled, by = \"city\")\n\nggplot(compare, aes(x = n)) +\n  geom_hline(yintercept = grand_mean, linetype = \"dashed\",\n             colour = \"#d32f2f\", linewidth = 1) +\n  geom_segment(aes(xend = n, y = raw_mean, yend = .epred),\n               colour = \"grey80\") +\n  geom_point(aes(y = raw_mean), colour = \"grey70\", size = 2.5) +\n  geom_point(aes(y = .epred), colour = \"#122a52\", size = 2.5) +\n  scale_x_log10() +\n  labs(title = \"Shrinkage: partial pooling pulls small offices inward\",\n       subtitle = \"Grey = raw average, navy = model estimate, red dashed = grand mean\",\n       x = \"Number of managers (log scale)\", y = \"Test score\")\n```\n\n::: {.cell-output-display}\n![](08-multilevel-models_files/figure-html/shrinkage-1.png){width=672}\n:::\n:::\n\n\n### Read it left to right\n\n-   **Left** (few managers) — long grey lines: extreme raw averages\n    pulled hard toward the middle\n-   **Right** (many managers) — barely any movement: the model trusts\n    them\n\n::: callout-important\nThe model worked out **how much to trust each office**, all by itself.\nNobody set a threshold, nobody dropped a small office, and nobody had\nto argue about where the cut-off should sit.\n:::\n\n------------------------------------------------------------------------\n\n## The other way people fix this: the funnel plot\n\nPartial pooling is not the only answer to the unequal-groups problem,\nand it is not the best known one. In healthcare and education, where\npublished league tables of hospitals and schools do real damage, the\nstandard tool is the **funnel plot**, popularised by David\nSpiegelhalter. It is worth knowing, both because you will meet it and\nbecause comparing the two makes clear what partial pooling actually\nbuys you.\n\nThe idea is simple. Plot each group's average against its sample size,\nthen draw the range within which an average would be expected to fall\n*if every group were identical*. That range is wide for small groups\nand narrow for large ones, so the boundaries form a funnel.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsigma_within <- managers |>                                        # <1>\n  group_by(city) |>\n  summarise(s = sd(test_score), n = n(), .groups = \"drop\") |>\n  summarise(pooled = sqrt(sum((n - 1) * s^2) / sum(n - 1))) |>\n  pull(pooled)\n\nfunnel <- tibble(n = seq(15, 230, length.out = 300)) |>\n  mutate(\n    lower = grand_mean - 2 * sigma_within / sqrt(n),               # <2>\n    upper = grand_mean + 2 * sigma_within / sqrt(n)\n  )\n\nggplot() +\n  geom_line(data = funnel, aes(n, lower), colour = \"grey70\", linetype = \"dashed\") +\n  geom_line(data = funnel, aes(n, upper), colour = \"grey70\", linetype = \"dashed\") +\n  geom_hline(yintercept = grand_mean, colour = \"#d32f2f\", linetype = \"dashed\") +\n  geom_point(data = raw, aes(n, raw_mean), colour = \"#122a52\", size = 3) +\n  geom_text(data = raw, aes(n, raw_mean, label = city),\n            nudge_y = 9, size = 3, colour = \"#122a52\") +\n  labs(\n    title = \"A funnel plot of the same six offices\",\n    subtitle = \"Grey dashed = the range you would expect if every office were identical; red dashed = overall mean\",\n    x = \"Number of managers\", y = \"Mean test score\"\n  )\n```\n\n::: {.cell-output-display}\n![](08-multilevel-models_files/figure-html/funnel-plot-1.png){width=672}\n:::\n:::\n\n\n1.  The pooled within-office standard deviation — how much individual\n    managers differ, averaged properly across offices of different\n    sizes.\n2.  The expected range for a group of size `n`, two standard errors\n    either side of the overall mean. This is the Chapter 3 formula\n    again, drawn as a curve instead of evaluated at one point.\n\nRead it by asking which points fall outside the funnel. Inside means\nthe office is no further from the average than sampling noise would\ncomfortably explain. The plot makes the small-office problem\nimpossible to miss: the funnel is so wide on the left that an office of\n23 managers has to be extraordinary before it counts as different at\nall.\n\n### Which should you use?\n\nThey answer different questions, and the difference is worth being\nprecise about.\n\nThe funnel plot asks, of each office separately: **could this\ndifference be chance?** It needs no model, takes one line to explain,\nand is very hard to argue with in a room. What it does not do is give\nyou a better number. It tells you which averages to ignore; it leaves\nthe averages themselves untouched.\n\nPartial pooling asks: **what is my best estimate for each office, given\neverything I know?** It answers for every office at once, produces a\nrevised number rather than a verdict, and carries its uncertainty with\nit.\n\n::: callout-important\nWhich means the answer to the stakeholder who wanted a ranking is not\n\"you can't have one\". **You can have a league table — just not one\nbuilt from raw averages.** Rank the partially pooled estimates instead.\nSmall offices will sit closer to the middle than they used to, which is\nthe honest position for them to occupy, and the ordering that survives\nis the ordering the evidence actually supports.\n\nThat is a much better conversation than refusing the request, and it is\nwhy this chapter ends with a model rather than a warning.\n:::\n\nThe two tools also work well together. The funnel plot is the better\npicture for showing an audience *why* the raw table was misleading; the\npooled estimates are the better basis for what you do next. Chapter 15\ntakes the second half of that much further, ranking 571 individual\nmanagers.\n\n------------------------------------------------------------------------\n\n\n::: callout-note\n## What to say when someone asks why the number changed\n\nYou will be asked this, and \"shrinkage\" is not the answer to give.\n\nThe version that works: *\"That office has eleven managers. If we\nreported their raw average we'd be treating eleven people's scores as\nthough they were as reliable as Toronto's two hundred, and they\naren't — with that few, the average could easily land several points\neither side by chance. So the estimate leans partly on what we know\nabout offices in general. As the office grows, it'll rely more on its\nown numbers and less on everyone else's.\"*\n\nThat's an argument about **how much evidence there is**, which\nstakeholders accept readily. It's the same argument you'd make against\ndeclaring a trend from two data points.\n:::\n\n### The multiple comparisons problem, quietly solved\n\nSomebody trained classically will now raise a hand. We have six\noffices. Comparing all of them against each other is fifteen\ncomparisons, and everyone learns that testing fifteen things at the\n5% level will hand you a \"significant\" result roughly half the time by\nchance alone. The classical fix is a **correction** — Bonferroni,\nTukey, false discovery rate — which widens every interval to buy back\nthe error rate you spent.\n\nWe haven't applied one, and we aren't going to. Here's why.\n\n::: callout-important\n## Partial pooling has already done the work\n\nThe classical problem arises because **no pooling** lets each office's\nestimate go wherever its own small sample points, and then asks\nfifteen questions of estimates that were free to wander. The\ncorrections are applied afterwards, to compensate.\n\nPartial pooling stops it happening in the first place. Every office's\nestimate has already been pulled towards the grand mean by an amount\nset by its sample size, so the extremes that generate spurious\n\"differences\" have been damped *before* any comparison is made. The\ngroup-level prior — `sd(Intercept)`, learned from the offices\ncollectively — is doing structurally what a multiplicity correction\ndoes by decree, except that the data chose the amount rather than a\nconvention.\n:::\n\nTwo things follow that are worth being precise about, because it is\neasy to overclaim here.\n\n1.  **This is a property of the multilevel model, not of Bayes on its\n    own.** A Bayesian model with a flat prior and no pooling would\n    reproduce the classical problem faithfully. It's the shared\n    distribution across groups — Chapter 5's point that a prior is a\n    constraint, applied here to a whole family of estimates at once —\n    that provides the protection. Gelman, Hill and Yajima make this\n    argument in full in *\"Why we (usually) don't have to worry about\n    multiple comparisons\"* [@gelman2012multiple]; it is the standard\n    reference if a stakeholder or a reviewer pushes.\n2.  **A credible interval doesn't change when you look at another\n    one.** This is the deeper reason the machinery differs. A\n    confidence interval is a statement about a procedure repeated over\n    hypothetical datasets, so how many intervals the procedure\n    produces changes what it guarantees. A posterior is a statement\n    about the parameters given the data you have — asking a second\n    question of the same posterior doesn't alter the answer to the\n    first. There is no error rate being spent, so there is nothing to\n    correct.\n\n::: callout-note\nNone of this licenses fishing. If you compute all fifteen contrasts\nand report the one that looks best, you'll mislead people with or\nwithout a correction — the honest move is to say how many you looked\nat. The claim is narrower and more useful: with partial pooling doing\nthe regularising, you don't need to inflate your intervals to make the\ncomparison legitimate.\n:::\n\n### Your turn {.unnumbered}\n\n**1.** Which office has the largest gap between its raw average and its\nmodel estimate? Confirm it's one with few managers.\n\n**2.** Refit with `prior(exponential(0.5), class = sd)` — a prior\ninsisting offices barely differ. Does shrinkage get stronger or\nweaker, and does that match the weighting formula from earlier?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Hint for 1: add a column = abs(raw_mean - .epred) and arrange().\n```\n:::\n\n\n------------------------------------------------------------------------\n\n## Predicting a brand-new office\n\nSuppose the business is opening in a city you have no managers in yet,\nand someone asks what to expect. Complete pooling would give you the\ngrand mean with no acknowledgement that offices differ. No pooling\ncan't answer at all — there's no group to look up.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(city = \"NEW_OFFICE\") |>\n  add_epred_draws(fit_ml, allow_new_levels = TRUE) |>    # <1>\n  mean_qi(.epred, .width = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 8\n  city        .row .epred .lower .upper .width .point .interval\n  <chr>      <int>  <dbl>  <dbl>  <dbl>  <dbl> <chr>  <chr>    \n1 NEW_OFFICE     1   236.   211.   256.   0.95 mean   qi       \n```\n\n\n:::\n:::\n\n\n1.  `allow_new_levels = TRUE` tells `brms` this group wasn't in the\n    training data and that's deliberate. It then draws a brand-new\n    office-level offset from the distribution it learned across the\n    six offices it *has* seen.\n\nThe estimate sits near the grand mean — sensible, since we know\nnothing specific — but the interval is **wider** than for any existing\noffice, because it now carries the uncertainty about how much offices\ndiffer *on top of* the usual uncertainty.\n\n::: callout-important\nThat's the payoff of modelling the group-level distribution rather\nthan just the groups. You get a defensible answer for a group you have\nnever observed, with honest uncertainty attached — and \"we opened a\nnew office, what should we expect?\" is a question People Analytics\nteams get asked constantly.\n:::\n\n::: callout-note\n## Where this goes next\n\nChapter 14 applies this exact idea in closed form, without fitting a\nfull model (empirical Bayes). Chapter 15 goes deeper on partial\npooling applied to *individual managers* rather than offices — the\nquestion most People Analytics teams actually get asked — and directly\ncompares this model to the classical mixed-effects model\n(`lme4::lmer()`) you may already know.\n\nTwo further descendants are worth knowing about now, so you recognise\nthem when they arrive. Chapter 16 turns `sd(Intercept)` from a caveat\ninto the headline finding, decomposing pay variation across levels of an\norganisation. And Chapter 17 attaches this same grouping term to a\n*survival* model — a **frailty** model, where each group gets its own\nbaseline risk of someone leaving. That last one is where this chapter's\nargument pays off most directly: it answers \"which managers lose people\nfaster than their teams explain?\" without the league table that started\nthis chapter.\n:::\n\n------------------------------------------------------------------------\n\n## On the job {.unnumbered}\n\n::: callout-important\n## Why this matters day to day\n\nIf your data is grouped — employees within managers, responses within\nteams, outcomes within regions — a multilevel model is usually the\n**correct** analysis, and a sophisticated stakeholder increasingly\nexpects it. It stops you over-claiming from small subgroups, borrows\nstrength across groups, and even lets you say something sensible about\na group you've never seen before.\n:::\n\n------------------------------------------------------------------------\n\n## Summary {.unnumbered}\n\n::: callout-note\n## Today you learned\n\n1.  Grouped data needs **multilevel models**; ignoring structure makes\n    you overconfident.\n2.  A **league table of group averages is partly a league table of\n    group sizes**. Put error bars on one and most of the ranking\n    dissolves.\n3.  **Partial pooling** sits between one-average-for-all and\n    a-separate-average-each — and beats both. Don't drop small groups\n    instead; you'd lose data and still have to defend the threshold.\n4.  How far each group moves is a **weighted average**, set by its\n    sample size relative to how much groups genuinely differ. The\n    model learns the second part from the groups collectively.\n5.  `(1 | group)` adds a **varying intercept** per group in `brms`.\n6.  **Shrinkage** pulls small-sample groups toward the grand mean —\n    and improves predictions. Explain it to stakeholders as an\n    argument about *how much evidence there is*, never by using the\n    word \"shrinkage\".\n7.  Partial pooling means you don't apply a **multiple comparisons\n    correction**. The pooling has already damped the extremes that\n    the correction exists to punish — and a credible interval doesn't\n    change because you looked at another one.\n8.  `sd(Intercept)` estimates **between-group spread**, itself a\n    finding — but it needs a decent **number of groups** to be\n    estimated well, and six is not many.\n9.  Multilevel models are the first place **sampling diagnostics stop\n    being automatic**. Check Rhat and ESS, and reach for\n    `adapt_delta`.\n10. With a group-level distribution in hand you can predict for a\n    group you've **never observed**.\n:::\n\n## Next chapter {.unnumbered}\n\n**Logistic regression** for a yes/no outcome, which HR has a large number of.\n",
    "supporting": [
      "08-multilevel-models_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}